# Test ingested data for the monthly run

In [1]:
# VIEWS 3
from viewser import Queryset, Column
from views_mapper2.label_writer import *
import numpy as np
import pandas as pd
import sqlalchemy

## Prepare query for given time period and country

In [2]:
# Call the function

def vid2date(i):
    year=str(ViewsMonth(i).year)
    month=str(ViewsMonth(i).month)
    return year+'/'+month

In [3]:
# Choose year and month below to print the correlated `month_id`

print(ViewsMonth.from_year_month(year=2026, month=1))

ViewsMonth(id=553) #=> year:2026, month:1

In [4]:
# Set period to query for

StartOfHistory = 520
EndOfHistory = 558

StartYear = 2010
EndYear = 2026

In [5]:
print(sqlalchemy.__version__)
print(pd.__version__)

1.4.54
1.5.3

In [6]:
# Set country to query for
name_date2cid('Nigeria','2017-07-01') # The date here is irrelevant

Country(79)

In [7]:

## Country name to country ID
country = name_date2cid('Nigeria','2017-07-01') # The date here is irrelevant'

In [8]:
country_id = country.id
country_id

79

## Create df with identifiers

In [9]:
# Identifiers

identifiers_cm = (Queryset("identifiers", "country_month")

.with_column(Column('year', from_loa = "country_year", from_column = 'year_id'))
.with_column(Column('month', from_loa = "month", from_column = 'month'))
.with_column(Column('isoab', from_loa = "country", from_column = 'isoab'))
.with_column(Column('country', from_loa = "country", from_column = 'name'))

)
      
identifiers_cm = identifiers_cm.publish().fetch()

print(f"A dataset with {len(identifiers_cm.columns)} columns, with "
      f"data between t {min(identifiers_cm.index.get_level_values(0))} "
      f"and {max(identifiers_cm.index.get_level_values(0))}. "
      f"({len(np.unique(identifiers_cm.index.get_level_values(1)))} units)"
     )

Queryset identifiers read successfully
A dataset with 4 columns, with data between t 1 and 852. (213 units)

In [10]:
identifiers_cm

                     year  month isoab              country
month_id country_id
1        1           1980      1   GUY               Guyana
         2           1980      1   SUR             Suriname
         3           1980      1   TTO  Trinidad and Tobago
         4           1980      1   VEN            Venezuela
         5           1980      1   WSM                Samoa
...                   ...    ...   ...                  ...
852      242         2050     12   TZA             Tanzania
         243         2050     12   MAR              Morocco
         244         2050     12   MRT           Mauritania
         245         2050     12   SDN                Sudan
         246         2050     12   SSD          South Sudan

[158230 rows x 4 columns]

## Create df with UCDP data

In [11]:
ucdp_data_cm = (Queryset("fatalities002_ucdp_cm", "country_month")

# GED

.with_column(Column("ucdp_ged_sb_best_sum", from_loa = "country_month", from_column = "ged_sb_best_sum_nokgi"))                   
#.with_column(Column("ucdp_ged_os_best_sum", from_loa = "country_month", from_column = "ged_os_best_sum_nokgi"))   
#.with_column(Column("ucdp_ged_ns_best_sum", from_loa = "country_month", from_column = "ged_ns_best_sum_nokgi"))   

)
      
ucdp_data_cm = ucdp_data_cm.publish().fetch()

print(f"A dataset with {len(ucdp_data_cm.columns)} columns, with "
      f"data between t {min(ucdp_data_cm.index.get_level_values(0))} "
      f"and {max(ucdp_data_cm.index.get_level_values(0))}. "
      f"({len(np.unique(ucdp_data_cm.index.get_level_values(1)))} units)"
     )

Queryset fatalities002_ucdp_cm read successfully
A dataset with 1 columns, with data between t 1 and 852. (213 units)

In [12]:
ucdp_data_cm.describe()

       ucdp_ged_sb_best_sum
count          84342.000000
mean              31.429999
std              472.597528
min                0.000000
25%                0.000000
50%                0.000000
75%                0.000000
max            56186.000000

In [13]:
ucdp_data_cm

                     ucdp_ged_sb_best_sum
month_id country_id
1        1                            NaN
         2                            NaN
         3                            NaN
         4                            NaN
         5                            NaN
...                                   ...
852      242                          NaN
         243                          NaN
         244                          NaN
         245                          NaN
         246                          NaN

[158230 rows x 1 columns]

In [14]:
# Merge identifier df with data df

cols = ["country_id", "month_id"]

ucdp_data_cm_w_identifiers = pd.merge(identifiers_cm, ucdp_data_cm, on=cols, how="left")

ucdp_data_cm_w_identifiers

,,year,month,isoab,country,ucdp_ged_sb_best_sum
country_id,month_id,,,,,
1,1,1980,1,GUY,Guyana,NaN
2,1,1980,1,SUR,Suriname,NaN
3,1,1980,1,TTO,Trinidad and Tobago,NaN
4,1,1980,1,VEN,Venezuela,NaN
5,1,1980,1,WSM,Samoa,NaN
...,...,...,...,...,...,...
242,852,2050,12,TZA,Tanzania,NaN
243,852,2050,12,MAR,Morocco,NaN
244,852,2050,12,MRT,Mauritania,NaN
245,852,2050,12,SDN,Sudan,NaN
246,852,2050,12,SSD,South Sudan,NaN

In [15]:
# UPDATED SUBSET + GED

ged_cm_subset= ucdp_data_cm_w_identifiers.query(f'month_id >= {StartOfHistory} & month_id <= {EndOfHistory} & country_id == {country_id}')

ged_cm_subset # displays the subset

                     year  month isoab  country  ucdp_ged_sb_best_sum
country_id month_id
79         520       2023      4   NGA  Nigeria                 113.0
           521       2023      5   NGA  Nigeria                 131.0
           522       2023      6   NGA  Nigeria                 347.0
           523       2023      7   NGA  Nigeria                 288.0
           524       2023      8   NGA  Nigeria                  51.0
           525       2023      9   NGA  Nigeria                 107.0
           526       2023     10   NGA  Nigeria                 124.0
           527       2023     11   NGA  Nigeria                 342.0
           528       2023     12   NGA  Nigeria                 104.0
           529       2024      1   NGA  Nigeria                 132.0
           530       2024      2   NGA  Nigeria                 100.0
           531       2024      3   NGA  Nigeria                 135.0
           532       2024      4   NGA  Nigeria                 153.0
           533       2024      5   NGA  Nigeria                 117.0
           534       2024      6   NGA  Nigeria                  55.0
           535       2024      7   NGA  Nigeria                  73.0
           536       2024      8   NGA  Nigeria                 128.0
           537       2024      9   NGA  Nigeria                  53.0
           538       2024     10   NGA  Nigeria                 252.0
           539       2024     11   NGA  Nigeria                 195.0
           540       2024     12   NGA  Nigeria                  90.0
           541       2025      1   NGA  Nigeria                 200.0
           542       2025      2   NGA  Nigeria                  43.0
           543       2025      3   NGA  Nigeria                 135.0
           544       2025      4   NGA  Nigeria                  65.0
           545       2025      5   NGA  Nigeria                 313.0
           546       2025      6   NGA  Nigeria                 165.0
           547       2025      7   NGA  Nigeria                  66.0
           548       2025      8   NGA  Nigeria                 125.0
           549       2025      9   NGA  Nigeria                 217.0
           550       2025     10   NGA  Nigeria                 175.0
           551       2025     11   NGA  Nigeria                 126.0
           552       2025     12   NGA  Nigeria                 243.0
           553       2026      1   NGA  Nigeria                 387.0
           554       2026      2   NGA  Nigeria                 181.0
           555       2026      3   NGA  Nigeria                 485.0
           556       2026      4   NGA  Nigeria                 546.0
           557       2026      5   NGA  Nigeria                 720.0
           558       2026      6   NGA  Nigeria                 238.0

## Create df with ACLED data

In [16]:
acled_data_cm = (Queryset("fatalities002_acled_cm", "country_month")

# ACLED

.with_column(Column("acled_sb_count", from_loa = "country_month", from_column = "acled_sb_count"))                   
.with_column(Column("acled_sb_fat", from_loa = "country_month", from_column = "acled_sb_fat"))                   
.with_column(Column("acled_os_fat", from_loa = "country_month", from_column = "acled_os_fat"))   
.with_column(Column("acled_ns_fat", from_loa = "country_month", from_column = "acled_ns_fat"))   
.with_column(Column("acled_bat_gov_fat", from_loa = "country_month", from_column = "acled_bat_gov_fat"))  
.with_column(Column("acled_bat_reb_fat", from_loa = "country_month", from_column = "acled_bat_reb_fat"))                   
.with_column(Column("acled_pr_count", from_loa = "country_month", from_column = "acled_pr_count")) 
.with_column(Column("acled_prx_count", from_loa = "country_month", from_column = "acled_prx_count")) 
.with_column(Column("acled_prx_fat", from_loa = "country_month", from_column = "acled_prx_fat"))                   

)
      
acled_data_cm = acled_data_cm.publish().fetch()

print(f"A dataset with {len(acled_data_cm.columns)} columns, with "
      f"data between t {min(acled_data_cm.index.get_level_values(0))} "
      f"and {max(acled_data_cm.index.get_level_values(0))}. "
      f"({len(np.unique(acled_data_cm.index.get_level_values(1)))} units)"
     )

Queryset fatalities002_acled_cm read successfully
A dataset with 9 columns, with data between t 1 and 852. (213 units)

In [17]:
acled_data_cm

                     acled_sb_count  acled_sb_fat  acled_os_fat  acled_ns_fat  \
month_id country_id
1        1                      NaN           NaN           NaN           NaN
         2                      NaN           NaN           NaN           NaN
         3                      NaN           NaN           NaN           NaN
         4                      NaN           NaN           NaN           NaN
         5                      NaN           NaN           NaN           NaN
...                             ...           ...           ...           ...
852      242                    NaN           NaN           NaN           NaN
         243                    NaN           NaN           NaN           NaN
         244                    NaN           NaN           NaN           NaN
         245                    NaN           NaN           NaN           NaN
         246                    NaN           NaN           NaN           NaN

                     acled_bat_gov_fat  acled_bat_reb_fat  acled_pr_count  \
month_id country_id
1        1                         NaN                NaN             NaN
         2                         NaN                NaN             NaN
         3                         NaN                NaN             NaN
         4                         NaN                NaN             NaN
         5                         NaN                NaN             NaN
...                                ...                ...             ...
852      242                       NaN                NaN             NaN
         243                       NaN                NaN             NaN
         244                       NaN                NaN             NaN
         245                       NaN                NaN             NaN
         246                       NaN                NaN             NaN

                     acled_prx_count  acled_prx_fat
month_id country_id
1        1                       NaN            NaN
         2                       NaN            NaN
         3                       NaN            NaN
         4                       NaN            NaN
         5                       NaN            NaN
...                              ...            ...
852      242                     NaN            NaN
         243                     NaN            NaN
         244                     NaN            NaN
         245                     NaN            NaN
         246                     NaN            NaN

[158230 rows x 9 columns]

In [18]:
acled_data_cm.describe()

,acled_sb_count,acled_sb_fat,acled_os_fat,acled_ns_fat,acled_bat_gov_fat,acled_bat_reb_fat,acled_pr_count,acled_prx_count,acled_prx_fat
count,67134.000000,67134.000000,67134.000000,67134.000000,67134.000000,67134.000000,67134.000000,67134.000000,67134.000000
mean,10.601975,20.572288,9.264203,4.655435,0.927384,0.655614,17.425418,1.485298,0.755698
std,143.262667,300.710055,68.474146,38.782313,19.345386,13.880663,99.085983,9.074185,107.000061
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
max,7242.000000,39588.000000,5237.000000,2051.000000,2054.000000,2000.000000,6572.000000,455.000000,27633.000000

In [19]:
# Merge identifier df with data df

cols = ["country_id", "month_id"]

acled_data_cm_w_identifiers = pd.merge(identifiers_cm, acled_data_cm, on=cols, how="left")

acled_data_cm_w_identifiers

,,year,month,isoab,country,acled_sb_count,acled_sb_fat,acled_os_fat,acled_ns_fat,acled_bat_gov_fat,acled_bat_reb_fat,acled_pr_count,acled_prx_count,acled_prx_fat
country_id,month_id,,,,,,,,,,,,,
1,1,1980,1,GUY,Guyana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1980,1,SUR,Suriname,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1980,1,TTO,Trinidad and Tobago,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1980,1,VEN,Venezuela,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1,1980,1,WSM,Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,852,2050,12,TZA,Tanzania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243,852,2050,12,MAR,Morocco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,852,2050,12,MRT,Mauritania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,852,2050,12,SDN,Sudan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246,852,2050,12,SSD,South Sudan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
# Query the data – OLD version

acled_cm_subset= acled_data_cm_w_identifiers.query(f'month_id >= {StartOfHistory} & month_id <= {EndOfHistory} & country_id == {country_id}')

acled_cm_subset # displays the subset

                     year  month isoab  country  acled_sb_count  acled_sb_fat  \
country_id month_id
79         520       2023      4   NGA  Nigeria            62.0         269.0
           521       2023      5   NGA  Nigeria            47.0         121.0
           522       2023      6   NGA  Nigeria            44.0         309.0
           523       2023      7   NGA  Nigeria            65.0         267.0
           524       2023      8   NGA  Nigeria            61.0         181.0
           525       2023      9   NGA  Nigeria            49.0         222.0
           526       2023     10   NGA  Nigeria            76.0         300.0
           527       2023     11   NGA  Nigeria            88.0         373.0
           528       2023     12   NGA  Nigeria            81.0         253.0
           529       2024      1   NGA  Nigeria            96.0         293.0
           530       2024      2   NGA  Nigeria            23.0          60.0
           531       2024      3   NGA  Nigeria            99.0         320.0
           532       2024      4   NGA  Nigeria            84.0         445.0
           533       2024      5   NGA  Nigeria            72.0         202.0
           534       2024      6   NGA  Nigeria            59.0         290.0
           535       2024      7   NGA  Nigeria            80.0         293.0
           536       2024      8   NGA  Nigeria            52.0         259.0
           537       2024      9   NGA  Nigeria            58.0         222.0
           538       2024     10   NGA  Nigeria            52.0         149.0
           539       2024     11   NGA  Nigeria            67.0         351.0
           540       2024     12   NGA  Nigeria            55.0         228.0
           541       2025      1   NGA  Nigeria            66.0         847.0
           542       2025      2   NGA  Nigeria            53.0         194.0
           543       2025      3   NGA  Nigeria            74.0         455.0
           544       2025      4   NGA  Nigeria            57.0         279.0
           545       2025      5   NGA  Nigeria            69.0         448.0
           546       2025      6   NGA  Nigeria            46.0         336.0
           547       2025      7   NGA  Nigeria            76.0         302.0
           548       2025      8   NGA  Nigeria           103.0         436.0
           549       2025      9   NGA  Nigeria           143.0         530.0
           550       2025     10   NGA  Nigeria           103.0         591.0
           551       2025     11   NGA  Nigeria           137.0         505.0
           552       2025     12   NGA  Nigeria           134.0         402.0
           553       2026      1   NGA  Nigeria           156.0         565.0
           554       2026      2   NGA  Nigeria           112.0         318.0
           555       2026      3   NGA  Nigeria           230.0         946.0
           556       2026      4   NGA  Nigeria           275.0         953.0
           557       2026      5   NGA  Nigeria           257.0        1155.0
           558       2026      6   NGA  Nigeria           218.0         413.0

                     acled_os_fat  acled_ns_fat  acled_bat_gov_fat  \
country_id month_id
79         520              258.0         305.0                0.0
           521              263.0         227.0                0.0
           522              401.0         134.0                0.0
           523              239.0         112.0                0.0
           524              207.0         293.0                0.0
           525              169.0          97.0                0.0
           526              221.0          96.0                0.0
           527              226.0         244.0                0.0
           528              380.0         194.0                0.0
           529              302.0         144.0                0.0
           530              102.0         124.0                0.0
           531              362.0         180.0                0.0
           532              276.0         380.0                0.0
           533              482.0         255.0                0.0
           534              265.0         289.0                0.0
           535              205.0         168.0                0.0
           536              269.0         307.0                0.0
           537              185.0         170.0                0.0
           538              231.0         128.0                0.0
           539              208.0         234.0                0.0
           540              389.0         150.0                0.0
           541              346.0         157.0                0.0
           542              224.0         116.0                0.0
           543              178.0         140.0                0.0
           544              336.0         180.0                0.0
           545              512.0         115.0                0.0
           546              474.0         309.0                0.0
           547              266.0         166.0                0.0
           548              316.0          84.0                0.0
           549              256.0          54.0                0.0
           550              513.0         162.0                0.0
           551              282.0         116.0                0.0
           552              349.0          37.0                0.0
           553              376.0         105.0                0.0
           554              579.0          61.0                0.0
           555              462.0          67.0               12.0
           556              634.0         199.0                0.0
           557              596.0         110.0                0.0
           558              602.0         117.0                0.0

                     acled_bat_reb_fat  acled_pr_count  acled_prx_count  \
country_id month_id
79         520                     0.0            50.0             13.0
           521                     0.0            52.0              6.0
           522                     0.0            40.0              5.0
           523                     0.0            35.0              6.0
           524                     0.0           103.0              7.0
           525                     0.0            76.0              6.0
           526                     0.0            76.0             10.0
           527                     0.0            70.0             17.0
           528                     0.0            63.0             13.0
           529                     0.0            38.0              5.0
           530                     0.0            50.0              8.0
           531                     0.0            57.0             13.0
           532                     0.0            61.0             13.0
           533                     0.0            97.0             17.0
           534                     0.0            81.0             11.0
           535                     0.0            91.0             13.0
           536                     0.0           151.0             66.0
           537                     0.0            47.0              7.0
           538                     0.0            50.0             13.0
           539                     0.0            42.0              1.0
           540                     0.0            27.0              8.0
           541                     0.0            31.0              4.0
           542                     0.0            34.0             10.0
           543                     0.0            45.0             14.0
           544                     0.0            68.0              9.0
           545                     0.0            71.0             10.0
           546                     0.0            60.0              8.0
           547                     0.0            79.0              4.0
           548                     0.0            66.0              7.0
           549                     0.0            52.0              9.0
           550                     0.0            47.0             10.0
           551                     0.0            41.0              5.0
           552                     0.0            45.0              8.0
           553                     0.0            46.0              5.0
           554                     0.0            52.0              4.0
           555                    21.0            82.0             12.0
           556                     0.0            51.0              2.0
           557                     0.0            66.0              5.0
           558                    12.0            90.0              5.0

                     acled_prx_fat
country_id month_id
79         520                 4.0
           521                 3.0
           522                 4.0
           523                 5.0
           524                 2.0
           525                 1.0
           526                 7.0
           527                 4.0
           528                 5.0
           529                 3.0
           530                 0.0
           531                10.0
           532                12.0
           533                16.0
           534                 3.0
           535                 7.0
           536                30.0
           537                 0.0
           538                 1.0
           539                 1.0
           540                 1.0
           541                 1.0
           542                 8.0
           543                 7.0
           544                 1.0
           545                 4.0
           546                 2.0
           547                 1.0
           548                 3.0
           549                 3.0
           550                 5.0
           551                 5.0
           552                 9.0
           553                 0.0
           554                 3.0
           555                 4.0
           556                 1.0
           557                 3.0
           558                 2.0

## Create df with Topics data

In [21]:
topics_data_cm = (Queryset("fatalities002_topics_cm", "country_month")

# GED

.with_column(Column("randomly_selected__column", from_loa = "country_month", from_column = "topic_ste_theta13"))                   
)
      
topics_data_cm = topics_data_cm.publish().fetch()

print(f"A dataset with {len(topics_data_cm.columns)} columns, with "
      f"data between t {min(topics_data_cm.index.get_level_values(0))} "
      f"and {max(topics_data_cm.index.get_level_values(0))}. "
      f"({len(np.unique(topics_data_cm.index.get_level_values(1)))} units)"
     )

Queryset fatalities002_topics_cm read successfully
A dataset with 1 columns, with data between t 1 and 852. (213 units)

In [22]:
topics_data_cm.describe()

       randomly_selected__column
count               72257.000000
mean                    0.099379
std                     0.082062
min                     0.000817
25%                     0.039194
50%                     0.078093
75%                     0.136728
max                     0.857599

In [23]:
# Merge identifier df with data df

cols = ["country_id", "month_id"]

topics_data_cm_w_identifiers = pd.merge(identifiers_cm, topics_data_cm, on=cols, how="left")

topics_data_cm_w_identifiers

,,year,month,isoab,country,randomly_selected__column
country_id,month_id,,,,,
1,1,1980,1,GUY,Guyana,NaN
2,1,1980,1,SUR,Suriname,NaN
3,1,1980,1,TTO,Trinidad and Tobago,NaN
4,1,1980,1,VEN,Venezuela,NaN
5,1,1980,1,WSM,Samoa,NaN
...,...,...,...,...,...,...
242,852,2050,12,TZA,Tanzania,NaN
243,852,2050,12,MAR,Morocco,NaN
244,852,2050,12,MRT,Mauritania,NaN
245,852,2050,12,SDN,Sudan,NaN
246,852,2050,12,SSD,South Sudan,NaN

In [24]:
# Query the data

topics_cm_subset= topics_data_cm_w_identifiers.query(f'month_id >= {StartOfHistory} & month_id <= {EndOfHistory} & country_id == {country_id}')

topics_cm_subset # displays the subset

                     year  month isoab  country  randomly_selected__column
country_id month_id
79         520       2023      4   NGA  Nigeria                   0.006906
           521       2023      5   NGA  Nigeria                   0.005308
           522       2023      6   NGA  Nigeria                   0.009012
           523       2023      7   NGA  Nigeria                   0.023991
           524       2023      8   NGA  Nigeria                   0.026111
           525       2023      9   NGA  Nigeria                   0.053595
           526       2023     10   NGA  Nigeria                   0.029629
           527       2023     11   NGA  Nigeria                   0.012815
           528       2023     12   NGA  Nigeria                   0.021678
           529       2024      1   NGA  Nigeria                   0.022688
           530       2024      2   NGA  Nigeria                   0.014848
           531       2024      3   NGA  Nigeria                   0.008337
           532       2024      4   NGA  Nigeria                   0.025571
           533       2024      5   NGA  Nigeria                   0.030608
           534       2024      6   NGA  Nigeria                   0.007114
           535       2024      7   NGA  Nigeria                   0.012400
           536       2024      8   NGA  Nigeria                   0.026699
           537       2024      9   NGA  Nigeria                   0.011847
           538       2024     10   NGA  Nigeria                   0.025146
           539       2024     11   NGA  Nigeria                   0.038014
           540       2024     12   NGA  Nigeria                   0.025269
           541       2025      1   NGA  Nigeria                   0.049897
           542       2025      2   NGA  Nigeria                   0.011995
           543       2025      3   NGA  Nigeria                   0.031263
           544       2025      4   NGA  Nigeria                   0.035174
           545       2025      5   NGA  Nigeria                   0.019883
           546       2025      6   NGA  Nigeria                   0.026677
           547       2025      7   NGA  Nigeria                   0.020889
           548       2025      8   NGA  Nigeria                   0.035797
           549       2025      9   NGA  Nigeria                   0.026527
           550       2025     10   NGA  Nigeria                   0.025856
           551       2025     11   NGA  Nigeria                   0.043059
           552       2025     12   NGA  Nigeria                   0.123608
           553       2026      1   NGA  Nigeria                   0.117618
           554       2026      2   NGA  Nigeria                   0.054582
           555       2026      3   NGA  Nigeria                   0.112565
           556       2026      4   NGA  Nigeria                   0.066924
           557       2026      5   NGA  Nigeria                   0.069964
           558       2026      6   NGA  Nigeria                        NaN

## Create df with V-Dem data

In [ ]:
vdem_data_cm = (Queryset("fatalities003_vdem_cm", "country_year")

# V-Dem

.with_column(Column("vdem_v2x_libdem", from_loa = "country_year", from_column = "vdem_v2x_libdem"))                   
)
      
vdem_data_cm = vdem_data_cm.publish().fetch()

print(f"A dataset with {len(vdem_data_cm.columns)} columns, with "
      f"data between t {min(vdem_data_cm.index.get_level_values(0))} "
      f"and {max(vdem_data_cm.index.get_level_values(0))}. "
      f"({len(np.unique(vdem_data_cm.index.get_level_values(1)))} units)"
     )

In [ ]:
vdem_data_cm.describe()

In [ ]:
vdem_data_cm

In [ ]:
# Fix discrepancies in column names

vdem_data_cm = (
    vdem_data_cm
    .reset_index()
    .rename(columns={'year_id': 'year'})
    .set_index(['year', 'country_id'])
)

In [ ]:
vdem_data_cm

In [ ]:
# Merge identifier df with data df

cols = ["country_id", "year"]

vdem_data_cm_w_identifiers = pd.merge(identifiers_cm, vdem_data_cm, on=cols, how="left")

vdem_data_cm_w_identifiers

In [ ]:
# Query the data

vdem_data_cm= vdem_data_cm.query(f'year >= 2023 & year <= 2026 & country_id == {country_id}')

vdem_data_cm # displays the subset

# WDI

In [25]:
wdi_data_cm = (Queryset("fatalities002_wdi_cm", "country_year")

# V-Dem

.with_column(Column("wb_wdi_ny_gdp_pcap_kd", from_loa = "country_year", from_column = "wdi_ny_gdp_pcap_kd"))
.with_column(Column("wb_wdi_sp_dyn_le00_in", from_loa = "country_year", from_column = "wdi_sp_dyn_le00_in"))                   
.with_column(Column("wb_wdi_se_prm_nenr", from_loa = "country_year", from_column = "wdi_se_prm_nenr"))                   
.with_column(Column("wb_wdi_sp_pop_totl", from_loa = "country_year", from_column = "wdi_sp_pop_totl"))                   
.with_column(Column("wb_wdi_sp_dyn_imrt_in", from_loa = "country_year", from_column = "wdi_sp_dyn_imrt_in"))                   
)
      
wdi_data_cm = wdi_data_cm.publish().fetch()

print(f"A dataset with {len(wdi_data_cm.columns)} columns, with "
      f"data between t {min(wdi_data_cm.index.get_level_values(0))} "
      f"and {max(wdi_data_cm.index.get_level_values(0))}. "
      f"({len(np.unique(wdi_data_cm.index.get_level_values(1)))} units)"
     )

Queryset fatalities002_wdi_cm read successfully
A dataset with 5 columns, with data between t 1900 and 2050. (220 units)

In [26]:
wdi_data_cm.describe()

,wb_wdi_ny_gdp_pcap_kd,wb_wdi_sp_dyn_le00_in,wb_wdi_se_prm_nenr,wb_wdi_sp_pop_totl,wb_wdi_sp_dyn_imrt_in
count,8224.000000,8284.000000,3714.000000,8.477000e+03,8206.000000
mean,12077.665657,67.667734,86.111799,3.384672e+07,36.787363
std,19154.808920,9.895619,16.141461,1.279225e+08,35.053763
min,164.700417,12.158000,14.308450,7.366000e+03,1.200000
25%,1406.809401,61.322000,84.198770,1.413419e+06,9.625000
50%,4086.379898,69.629000,92.259495,6.827227e+06,23.500000
75%,14015.422131,74.992780,96.426705,2.202148e+07,55.100000
max,247170.103807,86.497000,100.000000,1.463866e+09,239.900000

In [27]:
wdi_data_cm

                    wb_wdi_ny_gdp_pcap_kd  wb_wdi_sp_dyn_le00_in  \
year_id country_id
1900    4                             NaN                    NaN
        7                             NaN                    NaN
        8                             NaN                    NaN
        10                            NaN                    NaN
        11                            NaN                    NaN
...                                   ...                    ...
2050    242                           NaN                    NaN
        243                           NaN                    NaN
        244                           NaN                    NaN
        245                           NaN                    NaN
        246                           NaN                    NaN

                    wb_wdi_se_prm_nenr  wb_wdi_sp_pop_totl  \
year_id country_id
1900    4                          NaN                 NaN
        7                          NaN                 NaN
        8                          NaN                 NaN
        10                         NaN                 NaN
        11                         NaN                 NaN
...                                ...                 ...
2050    242                        NaN                 NaN
        243                        NaN                 NaN
        244                        NaN                 NaN
        245                        NaN                 NaN
        246                        NaN                 NaN

                    wb_wdi_sp_dyn_imrt_in
year_id country_id
1900    4                             NaN
        7                             NaN
        8                             NaN
        10                            NaN
        11                            NaN
...                                   ...
2050    242                           NaN
        243                           NaN
        244                           NaN
        245                           NaN
        246                           NaN

[20392 rows x 5 columns]

In [28]:
# Fix discrepancies in column names

wdi_data_cm = (
    wdi_data_cm
    .reset_index()
    .rename(columns={'year_id': 'year'})
    .set_index(['year', 'country_id'])
)

In [29]:
# Merge identifier df with data df

cols = ["country_id", "year"]

wdi_data_cm_w_identifiers = pd.merge(identifiers_cm, wdi_data_cm, on=cols, how="left")

wdi_data_cm_w_identifiers

,year,month,isoab,country,wb_wdi_ny_gdp_pcap_kd,wb_wdi_sp_dyn_le00_in,wb_wdi_se_prm_nenr,wb_wdi_sp_pop_totl,wb_wdi_sp_dyn_imrt_in
country_id,,,,,,,,,
1,1980,1,GUY,Guyana,3247.672768,60.808,NaN,774367.0,59.8
2,1980,1,SUR,Suriname,7110.251415,60.654,NaN,375377.0,NaN
3,1980,1,TTO,Trinidad and Tobago,8608.641031,66.507,86.2554,1121744.0,36.7
4,1980,1,VEN,Venezuela,4638.420510,68.179,NaN,15258218.0,35.9
5,1980,1,WSM,Samoa,2642.834121,64.961,NaN,164322.0,33.4
...,...,...,...,...,...,...,...,...,...
242,2050,12,TZA,Tanzania,NaN,NaN,NaN,NaN,NaN
243,2050,12,MAR,Morocco,NaN,NaN,NaN,NaN,NaN
244,2050,12,MRT,Mauritania,NaN,NaN,NaN,NaN,NaN
245,2050,12,SDN,Sudan,NaN,NaN,NaN,NaN,NaN
246,2050,12,SSD,South Sudan,NaN,NaN,NaN,NaN,NaN

In [30]:
# Query the data

wdi_data_cm= wdi_data_cm.query(f'year >= {StartYear} & year <= {EndYear} & country_id == {country_id}')

wdi_data_cm # displays the subset

,,wb_wdi_ny_gdp_pcap_kd,wb_wdi_sp_dyn_le00_in,wb_wdi_se_prm_nenr,wb_wdi_sp_pop_totl,wb_wdi_sp_dyn_imrt_in
year,country_id,,,,,
2010,79,2315.466765,51.315,64.13783,166642886.0,71.1
2011,79,2370.976571,51.490,NaN,171379598.0,70.0
2012,79,2403.653879,51.688,NaN,176200625.0,69.1
2013,79,2495.341066,51.827,NaN,181049443.0,68.5
2014,79,2583.615570,51.940,NaN,185896915.0,68.1
2015,79,2585.733607,51.939,NaN,190671878.0,68.0
2016,79,2481.814904,52.189,NaN,195443700.0,68.1
2017,79,2441.712364,52.397,NaN,200254579.0,68.3
2018,79,2431.778578,52.669,NaN,204938755.0,68.7
2019,79,2431.535285,53.009,NaN,209485641.0,69.1
2020,79,2228.686314,53.072,NaN,213996181.0,69.5
2021,79,2206.664063,53.455,NaN,218529286.0,69.9
2022,79,2254.290804,54.079,NaN,223150896.0,70.2
2023,79,2280.677772,54.462,NaN,227882945.0,70.1
2024,79,2324.597024,54.635,NaN,232679478.0,69.8
2025,79,2368.538663,NaN,NaN,237527782.0,NaN
2026,79,NaN,NaN,NaN,NaN,NaN

In [31]:
# Query the data

wdi_data_cm= wdi_data_cm.query(f'year >= {StartYear} & year <= {EndYear} & country_id == {country_id}')

wdi_data_cm # displays the subset

,,wb_wdi_ny_gdp_pcap_kd,wb_wdi_sp_dyn_le00_in,wb_wdi_se_prm_nenr,wb_wdi_sp_pop_totl,wb_wdi_sp_dyn_imrt_in
year,country_id,,,,,
2010,79,2315.466765,51.315,64.13783,166642886.0,71.1
2011,79,2370.976571,51.490,NaN,171379598.0,70.0
2012,79,2403.653879,51.688,NaN,176200625.0,69.1
2013,79,2495.341066,51.827,NaN,181049443.0,68.5
2014,79,2583.615570,51.940,NaN,185896915.0,68.1
2015,79,2585.733607,51.939,NaN,190671878.0,68.0
2016,79,2481.814904,52.189,NaN,195443700.0,68.1
2017,79,2441.712364,52.397,NaN,200254579.0,68.3
2018,79,2431.778578,52.669,NaN,204938755.0,68.7
2019,79,2431.535285,53.009,NaN,209485641.0,69.1
2020,79,2228.686314,53.072,NaN,213996181.0,69.5
2021,79,2206.664063,53.455,NaN,218529286.0,69.9
2022,79,2254.290804,54.079,NaN,223150896.0,70.2
2023,79,2280.677772,54.462,NaN,227882945.0,70.1
2024,79,2324.597024,54.635,NaN,232679478.0,69.8
2025,79,2368.538663,NaN,NaN,237527782.0,NaN
2026,79,NaN,NaN,NaN,NaN,NaN

# FAOSTAT CPI

In [ ]:
faostat_cpi_cm = (Queryset("fatalities002_faostat_cpi_cm", "country_month")

# FAOSTAT CPI

.with_column(Column("fao_cpi_consumer_prices_food_indices", from_loa = "country_month", from_column = "consumer_prices_food_indices"))
.with_column(Column("fao_cpi_consumer_prices_general_indices", from_loa = "country_month", from_column = "consumer_prices_general_indices"))                   
.with_column(Column("fao_cpi_food_price_inflation", from_loa = "country_month", from_column = "food_price_inflation"))  

)

faostat_cpi_cm = faostat_cpi_cm.publish().fetch()
print(f"A dataset with {len(faostat_cpi_cm.columns)} columns, with "
      f"data between t {min(faostat_cpi_cm.index.get_level_values(0))} "
      f"and {max(faostat_cpi_cm.index.get_level_values(0))}. "
      f"({len(np.unique(faostat_cpi_cm.index.get_level_values(1)))} units)"
     )

In [ ]:
faostat_cpi_cm.describe()

In [ ]:
faostat_cpi_cm

In [ ]:
# Merge identifier df with data df

cols = ["country_id", "month_id"]

faostat_cpi_cm_cm_w_identifiers = pd.merge(identifiers_cm, faostat_cpi_cm, on=cols, how="left")

faostat_cpi_cm_cm_w_identifiers

In [ ]:
# Query the data

faostat_cpi = faostat_cpi_cm_cm_w_identifiers.query(f'month_id >= {StartOfHistory} & month_id <= {EndOfHistory} & country_id == {country_id}')

faostat_cpi # displays the subset

In [ ]:
# Query the data

faostat_cpi = faostat_cpi_cm_cm_w_identifiers.query(f'month_id >= {StartOfHistory} & month_id <= {EndOfHistory} & country_id == {country_id}')

faostat_cpi # displays the subset

# FAOSTAT FSEC

In [ ]:
faostat_fsec_cm = (Queryset("fatalities002_faostat_fsec_cm", "country_year")

# FAOSTAT FSEC

.with_column(Column("fao_fsec_gdp_pc_ppp", from_loa = "country_year", from_column = "gdp_pc_ppp")) # not updated
.with_column(Column("fao_fsec_pol_stability", from_loa = "country_year", from_column = "pol_stability"))                   
.with_column(Column("fao_fsec_pcap_fprod_var", from_loa = "country_year", from_column = "pcap_fprod_var")) # not updated                  
.with_column(Column("fao_fsec_pcap_fsupply_var", from_loa = "country_year", from_column = "pcap_fsupply_var"))                   
.with_column(Column("fao_fsec_pct_pop_basicdrink", from_loa = "country_year", from_column = "pct_pop_basicdrink"))                   
.with_column(Column("fao_fsec_pct_pop_basicsani", from_loa = "country_year", from_column = "pct_pop_basicsani"))                   
.with_column(Column("fao_fsec_pct_und5_wasting", from_loa = "country_year", from_column = "pct_und5_wasting"))                   
.with_column(Column("fao_fsec_pct_und5_stunted", from_loa = "country_year", from_column = "pct_und5_stunted"))                   
.with_column(Column("fao_fsec_pct_und5_overweight", from_loa = "country_year", from_column = "pct_und5_overweight"))                   
.with_column(Column("fao_fsec_prev_adult_obesity", from_loa = "country_year", from_column = "prev_adult_obesity"))                   
.with_column(Column("fao_fsec_prev_repr_anemia", from_loa = "country_year", from_column = "prev_repr_anemia"))                   
.with_column(Column("fao_fsec_prev_infant_bfeed", from_loa = "country_year", from_column = "prev_infant_bfeed"))                   
.with_column(Column("fao_fsec_rail_density", from_loa = "country_year", from_column = "rail_density"))                   
.with_column(Column("fao_fsec_pct_pop_safedrink", from_loa = "country_year", from_column = "pct_pop_safedrink"))                   
.with_column(Column("fao_fsec_pct_pop_safesani", from_loa = "country_year", from_column = "pct_pop_safesani"))                   
.with_column(Column("fao_fsec_prev_lowbweight", from_loa = "country_year", from_column = "prev_lowbweight"))                   
.with_column(Column("fao_fsec_avg_adequate_diet", from_loa = "country_year", from_column = "avg_adequate_diet"))                   
.with_column(Column("fao_fsec_avg_fprod_value", from_loa = "country_year", from_column = "avg_fprod_value"))  # not updated                 
.with_column(Column("fao_fsec_kcal_pcap_day", from_loa = "country_year", from_column = "kcal_pcap_day"))    # not updated               
.with_column(Column("fao_fsec_kcal_pcap_day_cerotu", from_loa = "country_year", from_column = "kcal_pcap_day_cerotu"))           # not updated        
.with_column(Column("fao_fsec_avg_protein_pcap_day", from_loa = "country_year", from_column = "avg_protein_pcap_day"))                   
.with_column(Column("fao_fsec_avg_animalprotein_pcap_day", from_loa = "country_year", from_column = "avg_animalprotein_pcap_day"))                   
.with_column(Column("fao_fsec_pop_undernourished", from_loa = "country_year", from_column = "pop_undernourished"))                   
.with_column(Column("fao_fsec_pct_cereal_import", from_loa = "country_year", from_column = "pct_cereal_import"))                   
.with_column(Column("fao_fsec_pct_arable_land", from_loa = "country_year", from_column = "pct_arable_land"))                    
.with_column(Column("fao_fsec_pct_fimport_merch", from_loa = "country_year", from_column = "pct_fimport_merch"))                   
.with_column(Column("fao_fsec_pct_severe_finsecurity", from_loa = "country_year", from_column = "pct_severe_finsecurity"))                   
.with_column(Column("fao_fsec_pct_modsevere_finsecurity", from_loa = "country_year", from_column = "pct_modsevere_finsecurity"))                   
.with_column(Column("fao_fsec_pop_severe_finsecurity", from_loa = "country_year", from_column = "pop_severe_finsecurity"))                   
.with_column(Column("fao_fsec_pop_modsevere_finsecurity", from_loa = "country_year", from_column = "pop_modsevere_finsecurity"))                   
.with_column(Column("fao_fsec_avg_energy_req", from_loa = "country_year", from_column = "avg_energy_req"))                   
.with_column(Column("fao_fsec_avg_fatsupply", from_loa = "country_year", from_column = "avg_fatsupply"))                   
.with_column(Column("fao_fsec_hcc_coeff_dist", from_loa = "country_year", from_column = "hcc_coeff_dist"))                   
.with_column(Column("fao_fsec_caloric_loss_retail", from_loa = "country_year", from_column = "caloric_loss_retail"))      
.with_column(Column("fao_fsec_min_energy_req", from_loa = "country_year", from_column = "min_energy_req"))                  
)
      
faostat_fsec_cm = faostat_fsec_cm.publish().fetch()

print(f"A dataset with {len(faostat_fsec_cm.columns)} columns, with "
      f"data between t {min(faostat_fsec_cm.index.get_level_values(0))} "
      f"and {max(faostat_fsec_cm.index.get_level_values(0))}. "
      f"({len(np.unique(faostat_fsec_cm.index.get_level_values(1)))} units)"
     )

In [ ]:
faostat_fsec_cm.describe()

In [ ]:
# Fix discrepancies in column names

faostat_fsec_cm = (
    faostat_fsec_cm
    .reset_index()
    .rename(columns={'year_id': 'year'})
    .set_index(['year', 'country_id'])
)

In [ ]:
faostat_fsec_cm

In [ ]:
# Merge identifier df with data df

cols = ["country_id", "year"]

faostat_fsec_cm_w_identifiers = pd.merge(identifiers_cm, faostat_fsec_cm, on=cols, how="left")

faostat_fsec_cm_w_identifiers

In [ ]:
# Query the data

faostat_fsec_cm = faostat_fsec_cm.query(f'year >= {StartYear} & year <= {EndYear} & country_id == {country_id}')

faostat_fsec_cm # displays the subset

# FAOSTAT PP

In [ ]:
faostat_pp_cm = (Queryset("fatalities002_faostat_pp_cm", "country_month")

# FAOSTAT FSEC

.with_column(Column("fao_pp_meat_price", from_loa = "country_month", from_column = "meat_price")) 
.with_column(Column("fao_pp_milk_price", from_loa = "country_month", from_column = "milk_price"))                   
.with_column(Column("fao_pp_mp_price", from_loa = "country_month", from_column = "mp_price"))                  
.with_column(Column("fao_pp_sugar_price", from_loa = "country_month", from_column = "sugar_price"))                   
.with_column(Column("fao_pp_wheat_price", from_loa = "country_month", from_column = "wheat_price"))                   
)
       
faostat_pp_cm = faostat_pp_cm.publish().fetch()

print(f"A dataset with {len(faostat_pp_cm.columns)} columns, with "
      f"data between t {min(faostat_pp_cm.index.get_level_values(0))} "
      f"and {max(faostat_pp_cm.index.get_level_values(0))}. "
      f"({len(np.unique(faostat_pp_cm.index.get_level_values(1)))} units)"
     )

In [ ]:
faostat_pp_cm.describe()

In [ ]:
faostat_pp_cm

In [ ]:
# Merge identifier df with data df

cols = ["country_id", "month_id"]

faostat_pp_cm_cm_w_identifiers = pd.merge(identifiers_cm, faostat_pp_cm, on=cols, how="left")

faostat_pp_cm_cm_w_identifiers

In [ ]:
# Query the data

faostat_pp_cm = faostat_pp_cm_cm_w_identifiers.query(f'month_id >= {StartOfHistory} & month_id <= {EndOfHistory} & country_id == {country_id}')

faostat_pp_cm # displays the subset

In [ ]:
faostat_pp_cm_cm_w_identifiers.to_csv('faostat_pp_cm_cm_w_identifiers.csv')

In [ ]:
print("All done!")

# IMF WEO

In [ ]:
imf_weo_cm = (Queryset("fatalities002_imf_weo_cm", "country_month")

# FAOSTAT FSEC

.with_column(Column("imf_weo_ngdp_rpch", from_loa = "country_year", from_column = "imf_weo_ngdp_rpch")) 
.with_column(Column("imf_weo_ngdpd", from_loa = "country_year", from_column = "imf_weo_ngdpd"))                                    
)
       
imf_weo_cm = imf_weo_cm.publish().fetch()

print(f"A dataset with {len(imf_weo_cm.columns)} columns, with "
      f"data between t {min(imf_weo_cm.index.get_level_values(0))} "
      f"and {max(imf_weo_cm.index.get_level_values(0))}. "
      f"({len(np.unique(imf_weo_cm.index.get_level_values(1)))} units)"
     )

In [ ]:
imf_weo_cm.describe()

In [ ]:
imf_weo_cm

In [ ]:
# Merge identifier df with data df

cols = ["country_id", "month_id"]

imf_weo_cm_w_identifiers = pd.merge(identifiers_cm, imf_weo_cm, on=cols, how="left")

imf_weo_cm_w_identifiers

In [ ]:
# Query the data

imf_cm = imf_weo_cm_w_identifiers.query(f'month_id >= {StartOfHistory} & month_id <= {EndOfHistory} & country_id == {country_id}')

imf_cm # displays the subset

In [ ]:
print("All done!")