# Test ingested data for the monthly run

In [1]:
# VIEWS 3
from viewser import Queryset, Column
from views_mapper2.label_writer import *
import numpy as np
import pandas as pd
import sqlalchemy

## Prepare query for given time period and country

In [2]:
# Call the function

def vid2date(i):
    year=str(ViewsMonth(i).year)
    month=str(ViewsMonth(i).month)
    return year+'/'+month

In [3]:
# Choose year and month below to print the correlated `month_id`

print(ViewsMonth.from_year_month(year=2026, month=1))

ViewsMonth(id=553) #=> year:2026, month:1

In [4]:
# Set period to query for

StartOfHistory = 520
EndOfHistory = 561

StartYear = 2010
EndYear = 2026

In [5]:
print(sqlalchemy.__version__)
print(pd.__version__)

1.4.54
1.5.3

In [6]:
# Set country to query for
name_date2cid('Nigeria','2017-07-01') # The date here is irrelevant

Country(79)

In [7]:

## Country name to country ID
country = name_date2cid('Nigeria','2017-07-01') # The date here is irrelevant'

In [8]:
country_id = country.id
country_id

79

## Create df with identifiers

In [9]:
# Identifiers

identifiers_cm = (Queryset("identifiers", "country_month")

.with_column(Column('year', from_loa = "country_year", from_column = 'year_id'))
.with_column(Column('month', from_loa = "month", from_column = 'month'))
.with_column(Column('isoab', from_loa = "country", from_column = 'isoab'))
.with_column(Column('country', from_loa = "country", from_column = 'name'))

)
      
identifiers_cm = identifiers_cm.publish().fetch()

print(f"A dataset with {len(identifiers_cm.columns)} columns, with "
      f"data between t {min(identifiers_cm.index.get_level_values(0))} "
      f"and {max(identifiers_cm.index.get_level_values(0))}. "
      f"({len(np.unique(identifiers_cm.index.get_level_values(1)))} units)"
     )

Queryset identifiers read successfully
A dataset with 4 columns, with data between t 1 and 852. (213 units)

In [10]:
identifiers_cm

                     year  month isoab              country
month_id country_id
1        1           1980      1   GUY               Guyana
         2           1980      1   SUR             Suriname
         3           1980      1   TTO  Trinidad and Tobago
         4           1980      1   VEN            Venezuela
         5           1980      1   WSM                Samoa
...                   ...    ...   ...                  ...
852      242         2050     12   TZA             Tanzania
         243         2050     12   MAR              Morocco
         244         2050     12   MRT           Mauritania
         245         2050     12   SDN                Sudan
         246         2050     12   SSD          South Sudan

[158230 rows x 4 columns]

## Create df with UCDP data

In [93]:
ucdp_data_cm = (Queryset("fatalities002_ucdp_cm", "country_month")

# GED

.with_column(Column("ucdp_ged_sb_best_sum", from_loa = "country_month", from_column = "ged_sb_best_sum_nokgi"))                   
#.with_column(Column("ucdp_ged_os_best_sum", from_loa = "country_month", from_column = "ged_os_best_sum_nokgi"))   
#.with_column(Column("ucdp_ged_ns_best_sum", from_loa = "country_month", from_column = "ged_ns_best_sum_nokgi"))   

)
      
ucdp_data_cm = ucdp_data_cm.publish().fetch()

print(f"A dataset with {len(ucdp_data_cm.columns)} columns, with "
      f"data between t {min(ucdp_data_cm.index.get_level_values(0))} "
      f"and {max(ucdp_data_cm.index.get_level_values(0))}. "
      f"({len(np.unique(ucdp_data_cm.index.get_level_values(1)))} units)"
     )

Queryset fatalities002_ucdp_cm read successfully
A dataset with 1 columns, with data between t 1 and 852. (213 units)

In [94]:
ucdp_data_cm.describe()

       ucdp_ged_sb_best_sum
count          84724.000000
mean              31.495149
std              472.275137
min                0.000000
25%                0.000000
50%                0.000000
75%                0.000000
max            56186.000000

In [95]:
ucdp_data_cm

                     ucdp_ged_sb_best_sum
month_id country_id
1        1                            NaN
         2                            NaN
         3                            NaN
         4                            NaN
         5                            NaN
...                                   ...
852      242                          NaN
         243                          NaN
         244                          NaN
         245                          NaN
         246                          NaN

[158230 rows x 1 columns]

In [96]:
# Merge identifier df with data df

cols = ["country_id", "month_id"]

ucdp_data_cm_w_identifiers = pd.merge(identifiers_cm, ucdp_data_cm, on=cols, how="left")

ucdp_data_cm_w_identifiers

,,year,month,isoab,country,ucdp_ged_sb_best_sum
country_id,month_id,,,,,
1,1,1980,1,GUY,Guyana,NaN
2,1,1980,1,SUR,Suriname,NaN
3,1,1980,1,TTO,Trinidad and Tobago,NaN
4,1,1980,1,VEN,Venezuela,NaN
5,1,1980,1,WSM,Samoa,NaN
...,...,...,...,...,...,...
242,852,2050,12,TZA,Tanzania,NaN
243,852,2050,12,MAR,Morocco,NaN
244,852,2050,12,MRT,Mauritania,NaN
245,852,2050,12,SDN,Sudan,NaN
246,852,2050,12,SSD,South Sudan,NaN

In [106]:
# UPDATED SUBSET + GED

ged_cm_subset= ucdp_data_cm_w_identifiers.query(f'month_id >= {StartOfHistory} & month_id <= {EndOfHistory} & country_id == {country_id}')

ged_cm_subset # displays the subset

                     year  month isoab  country  ucdp_ged_sb_best_sum
country_id month_id
79         520       2023      4   NGA  Nigeria                 113.0
           521       2023      5   NGA  Nigeria                 131.0
           522       2023      6   NGA  Nigeria                 347.0
           523       2023      7   NGA  Nigeria                 288.0
           524       2023      8   NGA  Nigeria                  51.0
           525       2023      9   NGA  Nigeria                 107.0
           526       2023     10   NGA  Nigeria                 124.0
           527       2023     11   NGA  Nigeria                 342.0
           528       2023     12   NGA  Nigeria                 104.0
           529       2024      1   NGA  Nigeria                 132.0
           530       2024      2   NGA  Nigeria                 100.0
           531       2024      3   NGA  Nigeria                 135.0
           532       2024      4   NGA  Nigeria                 153.0
           533       2024      5   NGA  Nigeria                 117.0
           534       2024      6   NGA  Nigeria                  55.0
           535       2024      7   NGA  Nigeria                  73.0
           536       2024      8   NGA  Nigeria                 128.0
           537       2024      9   NGA  Nigeria                  53.0
           538       2024     10   NGA  Nigeria                 252.0
           539       2024     11   NGA  Nigeria                 195.0
           540       2024     12   NGA  Nigeria                  90.0
           541       2025      1   NGA  Nigeria                 200.0
           542       2025      2   NGA  Nigeria                  43.0
           543       2025      3   NGA  Nigeria                 135.0
           544       2025      4   NGA  Nigeria                  65.0
           545       2025      5   NGA  Nigeria                 313.0
           546       2025      6   NGA  Nigeria                 165.0
           547       2025      7   NGA  Nigeria                  66.0
           548       2025      8   NGA  Nigeria                 119.0
           549       2025      9   NGA  Nigeria                 217.0
           550       2025     10   NGA  Nigeria                 175.0
           551       2025     11   NGA  Nigeria                 126.0
           552       2025     12   NGA  Nigeria                 243.0
           553       2026      1   NGA  Nigeria                 377.0
           554       2026      2   NGA  Nigeria                 181.0
           555       2026      3   NGA  Nigeria                 485.0
           556       2026      4   NGA  Nigeria                 546.0
           557       2026      5   NGA  Nigeria                 714.0
           558       2026      6   NGA  Nigeria                 239.0
           559       2026      7   NGA  Nigeria                 223.0
           560       2026      8   NGA  Nigeria                 639.0
           561       2026      9   NGA  Nigeria                   NaN

## Create df with ACLED data

In [11]:
acled_data_cm = (Queryset("fatalities002_acled_cm", "country_month")

# ACLED

.with_column(Column("acled_sb_count", from_loa = "country_month", from_column = "acled_sb_count"))                   
.with_column(Column("acled_sb_fat", from_loa = "country_month", from_column = "acled_sb_fat"))                   
.with_column(Column("acled_os_fat", from_loa = "country_month", from_column = "acled_os_fat"))   
.with_column(Column("acled_ns_fat", from_loa = "country_month", from_column = "acled_ns_fat"))   
.with_column(Column("acled_bat_gov_fat", from_loa = "country_month", from_column = "acled_bat_gov_fat"))  
.with_column(Column("acled_bat_reb_fat", from_loa = "country_month", from_column = "acled_bat_reb_fat"))                   
.with_column(Column("acled_pr_count", from_loa = "country_month", from_column = "acled_pr_count")) 
.with_column(Column("acled_prx_count", from_loa = "country_month", from_column = "acled_prx_count")) 
.with_column(Column("acled_prx_fat", from_loa = "country_month", from_column = "acled_prx_fat"))                   

)
      
acled_data_cm = acled_data_cm.publish().fetch()

print(f"A dataset with {len(acled_data_cm.columns)} columns, with "
      f"data between t {min(acled_data_cm.index.get_level_values(0))} "
      f"and {max(acled_data_cm.index.get_level_values(0))}. "
      f"({len(np.unique(acled_data_cm.index.get_level_values(1)))} units)"
     )

Queryset fatalities002_acled_cm read successfully
A dataset with 9 columns, with data between t 1 and 852. (213 units)

In [12]:
acled_data_cm

                     acled_sb_count  acled_sb_fat  acled_os_fat  acled_ns_fat  \
month_id country_id
1        1                      NaN           NaN           NaN           NaN
         2                      NaN           NaN           NaN           NaN
         3                      NaN           NaN           NaN           NaN
         4                      NaN           NaN           NaN           NaN
         5                      NaN           NaN           NaN           NaN
...                             ...           ...           ...           ...
852      242                    NaN           NaN           NaN           NaN
         243                    NaN           NaN           NaN           NaN
         244                    NaN           NaN           NaN           NaN
         245                    NaN           NaN           NaN           NaN
         246                    NaN           NaN           NaN           NaN

                     acled_bat_gov_fat  acled_bat_reb_fat  acled_pr_count  \
month_id country_id
1        1                         NaN                NaN             NaN
         2                         NaN                NaN             NaN
         3                         NaN                NaN             NaN
         4                         NaN                NaN             NaN
         5                         NaN                NaN             NaN
...                                ...                ...             ...
852      242                       NaN                NaN             NaN
         243                       NaN                NaN             NaN
         244                       NaN                NaN             NaN
         245                       NaN                NaN             NaN
         246                       NaN                NaN             NaN

                     acled_prx_count  acled_prx_fat
month_id country_id
1        1                       NaN            NaN
         2                       NaN            NaN
         3                       NaN            NaN
         4                       NaN            NaN
         5                       NaN            NaN
...                              ...            ...
852      242                     NaN            NaN
         243                     NaN            NaN
         244                     NaN            NaN
         245                     NaN            NaN
         246                     NaN            NaN

[158230 rows x 9 columns]

In [13]:
acled_data_cm.describe()

,acled_sb_count,acled_sb_fat,acled_os_fat,acled_ns_fat,acled_bat_gov_fat,acled_bat_reb_fat,acled_pr_count,acled_prx_count,acled_prx_fat
count,67516.000000,67516.000000,67516.000000,67516.000000,67516.000000,67516.000000,67516.000000,67516.000000,67516.000000
mean,10.941866,20.719474,9.332321,4.661310,0.925914,0.655459,17.633702,1.495216,0.754458
std,149.336022,300.594633,68.517055,38.711182,19.298874,13.847330,99.897008,9.141858,106.697622
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
max,7727.000000,39588.000000,5237.000000,2051.000000,2054.000000,2000.000000,6572.000000,455.000000,27633.000000

In [14]:
# Merge identifier df with data df

cols = ["country_id", "month_id"]

acled_data_cm_w_identifiers = pd.merge(identifiers_cm, acled_data_cm, on=cols, how="left")

acled_data_cm_w_identifiers

,,year,month,isoab,country,acled_sb_count,acled_sb_fat,acled_os_fat,acled_ns_fat,acled_bat_gov_fat,acled_bat_reb_fat,acled_pr_count,acled_prx_count,acled_prx_fat
country_id,month_id,,,,,,,,,,,,,
1,1,1980,1,GUY,Guyana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1980,1,SUR,Suriname,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1980,1,TTO,Trinidad and Tobago,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1980,1,VEN,Venezuela,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1,1980,1,WSM,Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,852,2050,12,TZA,Tanzania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243,852,2050,12,MAR,Morocco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,852,2050,12,MRT,Mauritania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,852,2050,12,SDN,Sudan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246,852,2050,12,SSD,South Sudan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# Query the data – OLD version

acled_cm_subset= acled_data_cm_w_identifiers.query(f'month_id >= {StartOfHistory} & month_id <= {EndOfHistory} & country_id == {country_id}')

acled_cm_subset # displays the subset

                     year  month isoab  country  acled_sb_count  acled_sb_fat  \
country_id month_id
79         520       2023      4   NGA  Nigeria            62.0         269.0
           521       2023      5   NGA  Nigeria            47.0         121.0
           522       2023      6   NGA  Nigeria            44.0         309.0
           523       2023      7   NGA  Nigeria            65.0         267.0
           524       2023      8   NGA  Nigeria            61.0         181.0
           525       2023      9   NGA  Nigeria            49.0         222.0
           526       2023     10   NGA  Nigeria            76.0         300.0
           527       2023     11   NGA  Nigeria            88.0         373.0
           528       2023     12   NGA  Nigeria            81.0         253.0
           529       2024      1   NGA  Nigeria            96.0         293.0
           530       2024      2   NGA  Nigeria            23.0          60.0
           531       2024      3   NGA  Nigeria            99.0         320.0
           532       2024      4   NGA  Nigeria            84.0         445.0
           533       2024      5   NGA  Nigeria            72.0         202.0
           534       2024      6   NGA  Nigeria            59.0         290.0
           535       2024      7   NGA  Nigeria            80.0         293.0
           536       2024      8   NGA  Nigeria            52.0         259.0
           537       2024      9   NGA  Nigeria            58.0         222.0
           538       2024     10   NGA  Nigeria            52.0         149.0
           539       2024     11   NGA  Nigeria            67.0         351.0
           540       2024     12   NGA  Nigeria            55.0         228.0
           541       2025      1   NGA  Nigeria            66.0         847.0
           542       2025      2   NGA  Nigeria            53.0         194.0
           543       2025      3   NGA  Nigeria            74.0         455.0
           544       2025      4   NGA  Nigeria            57.0         279.0
           545       2025      5   NGA  Nigeria            69.0         448.0
           546       2025      6   NGA  Nigeria            46.0         336.0
           547       2025      7   NGA  Nigeria            76.0         302.0
           548       2025      8   NGA  Nigeria           103.0         436.0
           549       2025      9   NGA  Nigeria           143.0         530.0
           550       2025     10   NGA  Nigeria           103.0         591.0
           551       2025     11   NGA  Nigeria           137.0         505.0
           552       2025     12   NGA  Nigeria           134.0         402.0
           553       2026      1   NGA  Nigeria           156.0         565.0
           554       2026      2   NGA  Nigeria           112.0         318.0
           555       2026      3   NGA  Nigeria           230.0         946.0
           556       2026      4   NGA  Nigeria           275.0         953.0
           557       2026      5   NGA  Nigeria           257.0        1155.0
           558       2026      6   NGA  Nigeria           218.0         413.0
           559       2026      7   NGA  Nigeria           242.0         512.0
           560       2026      8   NGA  Nigeria           227.0         738.0
           561       2026      9   NGA  Nigeria             NaN           NaN

                     acled_os_fat  acled_ns_fat  acled_bat_gov_fat  \
country_id month_id
79         520              258.0         305.0                0.0
           521              263.0         227.0                0.0
           522              401.0         134.0                0.0
           523              239.0         112.0                0.0
           524              207.0         293.0                0.0
           525              169.0          97.0                0.0
           526              221.0          96.0                0.0
           527              226.0         244.0                0.0
           528              380.0         194.0                0.0
           529              302.0         144.0                0.0
           530              102.0         124.0                0.0
           531              362.0         180.0                0.0
           532              276.0         380.0                0.0
           533              482.0         255.0                0.0
           534              265.0         289.0                0.0
           535              205.0         168.0                0.0
           536              269.0         307.0                0.0
           537              185.0         170.0                0.0
           538              231.0         128.0                0.0
           539              208.0         234.0                0.0
           540              389.0         150.0                0.0
           541              346.0         157.0                0.0
           542              224.0         116.0                0.0
           543              178.0         140.0                0.0
           544              336.0         180.0                0.0
           545              512.0         115.0                0.0
           546              474.0         309.0                0.0
           547              266.0         166.0                0.0
           548              316.0          84.0                0.0
           549              256.0          54.0                0.0
           550              513.0         162.0                0.0
           551              282.0         116.0                0.0
           552              349.0          37.0                0.0
           553              376.0         105.0                0.0
           554              579.0          61.0                0.0
           555              462.0          67.0               12.0
           556              634.0         199.0                0.0
           557              596.0         110.0                0.0
           558              602.0         117.0                0.0
           559              466.0         109.0                0.0
           560              482.0         240.0                0.0
           561                NaN           NaN                NaN

                     acled_bat_reb_fat  acled_pr_count  acled_prx_count  \
country_id month_id
79         520                     0.0            50.0             13.0
           521                     0.0            52.0              6.0
           522                     0.0            40.0              5.0
           523                     0.0            35.0              6.0
           524                     0.0           103.0              7.0
           525                     0.0            76.0              6.0
           526                     0.0            76.0             10.0
           527                     0.0            70.0             17.0
           528                     0.0            63.0             13.0
           529                     0.0            38.0              5.0
           530                     0.0            50.0              8.0
           531                     0.0            57.0             13.0
           532                     0.0            61.0             13.0
           533                     0.0            97.0             17.0
           534                     0.0            81.0             11.0
           535                     0.0            91.0             13.0
           536                     0.0           151.0             66.0
           537                     0.0            47.0              7.0
           538                     0.0            50.0             13.0
           539                     0.0            42.0              1.0
           540                     0.0            27.0              8.0
           541                     0.0            31.0              4.0
           542                     0.0            34.0             10.0
           543                     0.0            45.0             14.0
           544                     0.0            68.0              9.0
           545                     0.0            71.0             10.0
           546                     0.0            60.0              8.0
           547                     0.0            79.0              4.0
           548                     0.0            66.0              7.0
           549                     0.0            52.0              9.0
           550                     0.0            47.0             10.0
           551                     0.0            41.0              5.0
           552                     0.0            45.0              8.0
           553                     0.0            46.0              5.0
           554                     0.0            52.0              4.0
           555                    21.0            82.0             12.0
           556                     0.0            51.0              2.0
           557                     0.0            66.0              5.0
           558                    12.0            90.0              5.0
           559                     0.0            46.0              2.0
           560                     0.0            50.0             12.0
           561                     NaN             NaN              NaN

                     acled_prx_fat
country_id month_id
79         520                 4.0
           521                 3.0
           522                 4.0
           523                 5.0
           524                 2.0
           525                 1.0
           526                 7.0
           527                 4.0
           528                 5.0
           529                 3.0
           530                 0.0
           531                10.0
           532                12.0
           533                16.0
           534                 3.0
           535                 7.0
           536                30.0
           537                 0.0
           538                 1.0
           539                 1.0
           540                 1.0
           541                 1.0
           542                 8.0
           543                 7.0
           544                 1.0
           545                 4.0
           546                 2.0
           547                 1.0
           548                 3.0
           549                 3.0
           550                 5.0
           551                 5.0
           552                 9.0
           553                 0.0
           554                 3.0
           555                 4.0
           556                 1.0
           557                 3.0
           558                 2.0
           559                 1.0
           560                 1.0
           561                 NaN

## Create df with Topics data

In [38]:
topics_data_cm = (Queryset("fatalities002_topics_cm", "country_month")

# GED

.with_column(Column("randomly_selected__column", from_loa = "country_month", from_column = "topic_ste_theta13"))                   
)
      
topics_data_cm = topics_data_cm.publish().fetch()

print(f"A dataset with {len(topics_data_cm.columns)} columns, with "
      f"data between t {min(topics_data_cm.index.get_level_values(0))} "
      f"and {max(topics_data_cm.index.get_level_values(0))}. "
      f"({len(np.unique(topics_data_cm.index.get_level_values(1)))} units)"
     )

Queryset fatalities002_topics_cm read successfully
A dataset with 1 columns, with data between t 1 and 852. (213 units)

In [39]:
topics_data_cm.describe()

       randomly_selected__column
count               72771.000000
mean                    0.099525
std                     0.082364
min                     0.000817
25%                     0.039191
50%                     0.078151
75%                     0.136902
max                     0.857599

In [40]:
# Merge identifier df with data df

cols = ["country_id", "month_id"]

topics_data_cm_w_identifiers = pd.merge(identifiers_cm, topics_data_cm, on=cols, how="left")

topics_data_cm_w_identifiers

,,year,month,isoab,country,randomly_selected__column
country_id,month_id,,,,,
1,1,1980,1,GUY,Guyana,NaN
2,1,1980,1,SUR,Suriname,NaN
3,1,1980,1,TTO,Trinidad and Tobago,NaN
4,1,1980,1,VEN,Venezuela,NaN
5,1,1980,1,WSM,Samoa,NaN
...,...,...,...,...,...,...
242,852,2050,12,TZA,Tanzania,NaN
243,852,2050,12,MAR,Morocco,NaN
244,852,2050,12,MRT,Mauritania,NaN
245,852,2050,12,SDN,Sudan,NaN
246,852,2050,12,SSD,South Sudan,NaN

In [108]:
# Query the data

topics_cm_subset= topics_data_cm_w_identifiers.query(f'month_id >= {StartOfHistory} & month_id <= {EndOfHistory} & country_id == {country_id}')

topics_cm_subset # displays the subset

                     year  month isoab  country  randomly_selected__column
country_id month_id
79         520       2023      4   NGA  Nigeria                   0.006906
           521       2023      5   NGA  Nigeria                   0.005308
           522       2023      6   NGA  Nigeria                   0.009012
           523       2023      7   NGA  Nigeria                   0.023991
           524       2023      8   NGA  Nigeria                   0.026111
           525       2023      9   NGA  Nigeria                   0.053595
           526       2023     10   NGA  Nigeria                   0.029629
           527       2023     11   NGA  Nigeria                   0.012815
           528       2023     12   NGA  Nigeria                   0.021678
           529       2024      1   NGA  Nigeria                   0.022688
           530       2024      2   NGA  Nigeria                   0.014848
           531       2024      3   NGA  Nigeria                   0.008337
           532       2024      4   NGA  Nigeria                   0.025571
           533       2024      5   NGA  Nigeria                   0.030608
           534       2024      6   NGA  Nigeria                   0.007114
           535       2024      7   NGA  Nigeria                   0.012400
           536       2024      8   NGA  Nigeria                   0.026699
           537       2024      9   NGA  Nigeria                   0.011847
           538       2024     10   NGA  Nigeria                   0.025146
           539       2024     11   NGA  Nigeria                   0.038014
           540       2024     12   NGA  Nigeria                   0.025269
           541       2025      1   NGA  Nigeria                   0.049897
           542       2025      2   NGA  Nigeria                   0.011995
           543       2025      3   NGA  Nigeria                   0.031263
           544       2025      4   NGA  Nigeria                   0.035174
           545       2025      5   NGA  Nigeria                   0.019883
           546       2025      6   NGA  Nigeria                   0.026677
           547       2025      7   NGA  Nigeria                   0.020889
           548       2025      8   NGA  Nigeria                   0.035797
           549       2025      9   NGA  Nigeria                   0.026527
           550       2025     10   NGA  Nigeria                   0.025856
           551       2025     11   NGA  Nigeria                   0.043059
           552       2025     12   NGA  Nigeria                   0.123608
           553       2026      1   NGA  Nigeria                   0.117618
           554       2026      2   NGA  Nigeria                   0.054582
           555       2026      3   NGA  Nigeria                   0.112565
           556       2026      4   NGA  Nigeria                   0.066924
           557       2026      5   NGA  Nigeria                   0.069964
           558       2026      6   NGA  Nigeria                   0.142586
           559       2026      7   NGA  Nigeria                   0.091840
           560       2026      8   NGA  Nigeria                   0.111476
           561       2026      9   NGA  Nigeria                        NaN

## Create df with V-Dem data

In [42]:
vdem_data_cm = (Queryset("fatalities003_vdem_cm", "country_year")

# V-Dem

.with_column(Column("vdem_v2x_libdem", from_loa = "country_year", from_column = "vdem_v2x_libdem"))                   
)
      
vdem_data_cm = vdem_data_cm.publish().fetch()

print(f"A dataset with {len(vdem_data_cm.columns)} columns, with "
      f"data between t {min(vdem_data_cm.index.get_level_values(0))} "
      f"and {max(vdem_data_cm.index.get_level_values(0))}. "
      f"({len(np.unique(vdem_data_cm.index.get_level_values(1)))} units)"
     )

Queryset fatalities003_vdem_cm read successfully
A dataset with 1 columns, with data between t 1900 and 2050. (220 units)

In [43]:
vdem_data_cm.describe()

       vdem_v2x_libdem
count      7590.000000
mean          0.370071
std           0.275583
min           0.005000
25%           0.115000
50%           0.307000
75%           0.623000
max           0.896000

In [44]:
vdem_data_cm

                    vdem_v2x_libdem
year_id country_id
1900    4                       NaN
        7                       NaN
        8                       NaN
        10                      NaN
        11                      NaN
...                             ...
2050    242                     NaN
        243                     NaN
        244                     NaN
        245                     NaN
        246                     NaN

[20392 rows x 1 columns]

In [45]:
# Fix discrepancies in column names

vdem_data_cm = (
    vdem_data_cm
    .reset_index()
    .rename(columns={'year_id': 'year'})
    .set_index(['year', 'country_id'])
)

In [46]:
vdem_data_cm

                 vdem_v2x_libdem
year country_id
1900 4                       NaN
     7                       NaN
     8                       NaN
     10                      NaN
     11                      NaN
...                          ...
2050 242                     NaN
     243                     NaN
     244                     NaN
     245                     NaN
     246                     NaN

[20392 rows x 1 columns]

In [47]:
# Merge identifier df with data df

cols = ["country_id", "year"]

vdem_data_cm_w_identifiers = pd.merge(identifiers_cm, vdem_data_cm, on=cols, how="left")

vdem_data_cm_w_identifiers

            year  month isoab              country  vdem_v2x_libdem
country_id
1           1980      1   GUY               Guyana            0.181
2           1980      1   SUR             Suriname            0.174
3           1980      1   TTO  Trinidad and Tobago            0.561
4           1980      1   VEN            Venezuela            0.590
5           1980      1   WSM                Samoa              NaN
...          ...    ...   ...                  ...              ...
242         2050     12   TZA             Tanzania              NaN
243         2050     12   MAR              Morocco              NaN
244         2050     12   MRT           Mauritania              NaN
245         2050     12   SDN                Sudan              NaN
246         2050     12   SSD          South Sudan              NaN

[158230 rows x 5 columns]

In [48]:
# Query the data

vdem_data_cm= vdem_data_cm.query(f'year >= 2023 & year <= 2026 & country_id == {country_id}')

vdem_data_cm # displays the subset

                 vdem_v2x_libdem
year country_id
2023 66                    0.849
2024 66                    0.846
2025 66                    0.853
2026 66                      NaN

# WDI

In [49]:
wdi_data_cm = (Queryset("fatalities002_wdi_cm", "country_year")

# V-Dem

.with_column(Column("wb_wdi_ny_gdp_pcap_kd", from_loa = "country_year", from_column = "wdi_ny_gdp_pcap_kd"))
.with_column(Column("wb_wdi_sp_dyn_le00_in", from_loa = "country_year", from_column = "wdi_sp_dyn_le00_in"))                   
.with_column(Column("wb_wdi_se_prm_nenr", from_loa = "country_year", from_column = "wdi_se_prm_nenr"))                   
.with_column(Column("wb_wdi_sp_pop_totl", from_loa = "country_year", from_column = "wdi_sp_pop_totl"))                   
.with_column(Column("wb_wdi_sp_dyn_imrt_in", from_loa = "country_year", from_column = "wdi_sp_dyn_imrt_in"))                   
)
      
wdi_data_cm = wdi_data_cm.publish().fetch()

print(f"A dataset with {len(wdi_data_cm.columns)} columns, with "
      f"data between t {min(wdi_data_cm.index.get_level_values(0))} "
      f"and {max(wdi_data_cm.index.get_level_values(0))}. "
      f"({len(np.unique(wdi_data_cm.index.get_level_values(1)))} units)"
     )

Queryset fatalities002_wdi_cm read successfully
A dataset with 5 columns, with data between t 1900 and 2050. (220 units)

In [50]:
wdi_data_cm.describe()

,wb_wdi_ny_gdp_pcap_kd,wb_wdi_sp_dyn_le00_in,wb_wdi_se_prm_nenr,wb_wdi_sp_pop_totl,wb_wdi_sp_dyn_imrt_in
count,8224.000000,8284.000000,3714.000000,8.477000e+03,8206.000000
mean,12077.665657,67.667734,86.111799,3.384672e+07,36.787363
std,19154.808920,9.895619,16.141461,1.279225e+08,35.053763
min,164.700417,12.158000,14.308450,7.366000e+03,1.200000
25%,1406.809401,61.322000,84.198770,1.413419e+06,9.625000
50%,4086.379898,69.629000,92.259495,6.827227e+06,23.500000
75%,14015.422131,74.992780,96.426705,2.202148e+07,55.100000
max,247170.103807,86.497000,100.000000,1.463866e+09,239.900000

In [51]:
wdi_data_cm

                    wb_wdi_ny_gdp_pcap_kd  wb_wdi_sp_dyn_le00_in  \
year_id country_id
1900    4                             NaN                    NaN
        7                             NaN                    NaN
        8                             NaN                    NaN
        10                            NaN                    NaN
        11                            NaN                    NaN
...                                   ...                    ...
2050    242                           NaN                    NaN
        243                           NaN                    NaN
        244                           NaN                    NaN
        245                           NaN                    NaN
        246                           NaN                    NaN

                    wb_wdi_se_prm_nenr  wb_wdi_sp_pop_totl  \
year_id country_id
1900    4                          NaN                 NaN
        7                          NaN                 NaN
        8                          NaN                 NaN
        10                         NaN                 NaN
        11                         NaN                 NaN
...                                ...                 ...
2050    242                        NaN                 NaN
        243                        NaN                 NaN
        244                        NaN                 NaN
        245                        NaN                 NaN
        246                        NaN                 NaN

                    wb_wdi_sp_dyn_imrt_in
year_id country_id
1900    4                             NaN
        7                             NaN
        8                             NaN
        10                            NaN
        11                            NaN
...                                   ...
2050    242                           NaN
        243                           NaN
        244                           NaN
        245                           NaN
        246                           NaN

[20392 rows x 5 columns]

In [52]:
# Fix discrepancies in column names

wdi_data_cm = (
    wdi_data_cm
    .reset_index()
    .rename(columns={'year_id': 'year'})
    .set_index(['year', 'country_id'])
)

In [53]:
# Merge identifier df with data df

cols = ["country_id", "year"]

wdi_data_cm_w_identifiers = pd.merge(identifiers_cm, wdi_data_cm, on=cols, how="left")

wdi_data_cm_w_identifiers

,year,month,isoab,country,wb_wdi_ny_gdp_pcap_kd,wb_wdi_sp_dyn_le00_in,wb_wdi_se_prm_nenr,wb_wdi_sp_pop_totl,wb_wdi_sp_dyn_imrt_in
country_id,,,,,,,,,
1,1980,1,GUY,Guyana,3247.672768,60.808,NaN,774367.0,59.8
2,1980,1,SUR,Suriname,7110.251415,60.654,NaN,375377.0,NaN
3,1980,1,TTO,Trinidad and Tobago,8608.641031,66.507,86.2554,1121744.0,36.7
4,1980,1,VEN,Venezuela,4638.420510,68.179,NaN,15258218.0,35.9
5,1980,1,WSM,Samoa,2642.834121,64.961,NaN,164322.0,33.4
...,...,...,...,...,...,...,...,...,...
242,2050,12,TZA,Tanzania,NaN,NaN,NaN,NaN,NaN
243,2050,12,MAR,Morocco,NaN,NaN,NaN,NaN,NaN
244,2050,12,MRT,Mauritania,NaN,NaN,NaN,NaN,NaN
245,2050,12,SDN,Sudan,NaN,NaN,NaN,NaN,NaN
246,2050,12,SSD,South Sudan,NaN,NaN,NaN,NaN,NaN

In [54]:
# Query the data

wdi_data_cm= wdi_data_cm.query(f'year >= {StartYear} & year <= {EndYear} & country_id == {country_id}')

wdi_data_cm # displays the subset

,,wb_wdi_ny_gdp_pcap_kd,wb_wdi_sp_dyn_le00_in,wb_wdi_se_prm_nenr,wb_wdi_sp_pop_totl,wb_wdi_sp_dyn_imrt_in
year,country_id,,,,,
2010,66,48205.549251,81.451220,99.38254,9378126.0,2.5
2011,66,49356.590526,81.802439,99.47861,9449213.0,2.5
2012,66,48789.790688,81.704878,99.60119,9519374.0,2.4
2013,66,48928.499414,81.956098,99.40873,9600379.0,2.4
2014,66,49557.618365,82.253659,99.46083,9696110.0,2.4
2015,66,51188.165212,82.204878,99.37978,9799186.0,2.3
2016,66,51626.323531,82.307317,99.34822,9923085.0,2.3
2017,66,51894.374818,82.409756,99.18177,10057698.0,2.3
2018,66,52203.087259,82.558537,NaN,10175214.0,2.2
2019,66,53024.409949,83.109756,NaN,10278887.0,2.2
2020,66,51624.581179,82.356098,NaN,10353442.0,2.1
2021,66,53997.133707,83.056098,NaN,10415811.0,2.1
2022,66,54304.187750,83.058537,NaN,10486941.0,2.0
2023,66,53937.796712,83.309756,NaN,10536632.0,2.0
2024,66,54316.261933,84.063415,NaN,10569709.0,2.0
2025,66,55014.381462,NaN,NaN,10596620.0,NaN
2026,66,NaN,NaN,NaN,NaN,NaN

In [55]:
# Query the data

wdi_data_cm= wdi_data_cm.query(f'year >= {StartYear} & year <= {EndYear} & country_id == {country_id}')

wdi_data_cm # displays the subset

,,wb_wdi_ny_gdp_pcap_kd,wb_wdi_sp_dyn_le00_in,wb_wdi_se_prm_nenr,wb_wdi_sp_pop_totl,wb_wdi_sp_dyn_imrt_in
year,country_id,,,,,
2010,66,48205.549251,81.451220,99.38254,9378126.0,2.5
2011,66,49356.590526,81.802439,99.47861,9449213.0,2.5
2012,66,48789.790688,81.704878,99.60119,9519374.0,2.4
2013,66,48928.499414,81.956098,99.40873,9600379.0,2.4
2014,66,49557.618365,82.253659,99.46083,9696110.0,2.4
2015,66,51188.165212,82.204878,99.37978,9799186.0,2.3
2016,66,51626.323531,82.307317,99.34822,9923085.0,2.3
2017,66,51894.374818,82.409756,99.18177,10057698.0,2.3
2018,66,52203.087259,82.558537,NaN,10175214.0,2.2
2019,66,53024.409949,83.109756,NaN,10278887.0,2.2
2020,66,51624.581179,82.356098,NaN,10353442.0,2.1
2021,66,53997.133707,83.056098,NaN,10415811.0,2.1
2022,66,54304.187750,83.058537,NaN,10486941.0,2.0
2023,66,53937.796712,83.309756,NaN,10536632.0,2.0
2024,66,54316.261933,84.063415,NaN,10569709.0,2.0
2025,66,55014.381462,NaN,NaN,10596620.0,NaN
2026,66,NaN,NaN,NaN,NaN,NaN

# FAOSTAT CPI

In [56]:
faostat_cpi_cm = (Queryset("fatalities002_faostat_cpi_cm", "country_month")

# FAOSTAT CPI

.with_column(Column("fao_cpi_consumer_prices_food_indices", from_loa = "country_month", from_column = "consumer_prices_food_indices"))
.with_column(Column("fao_cpi_consumer_prices_general_indices", from_loa = "country_month", from_column = "consumer_prices_general_indices"))                   
.with_column(Column("fao_cpi_food_price_inflation", from_loa = "country_month", from_column = "food_price_inflation"))  

)

faostat_cpi_cm = faostat_cpi_cm.publish().fetch()
print(f"A dataset with {len(faostat_cpi_cm.columns)} columns, with "
      f"data between t {min(faostat_cpi_cm.index.get_level_values(0))} "
      f"and {max(faostat_cpi_cm.index.get_level_values(0))}. "
      f"({len(np.unique(faostat_cpi_cm.index.get_level_values(1)))} units)"
     )

100%|██████████| 1.57M/1.57M [00:00<00:00, 14.3MB/s]

Queryset fatalities002_faostat_cpi_cm read successfully
A dataset with 3 columns, with data between t 1 and 852. (213 units)

In [57]:
faostat_cpi_cm.describe()

,fao_cpi_consumer_prices_food_indices,fao_cpi_consumer_prices_general_indices,fao_cpi_food_price_inflation
count,5.484400e+04,5.543200e+04,52768.000000
mean,1.045353e+09,7.414527e+08,50.945261
std,4.707968e+10,3.367753e+10,3050.423817
min,6.686770e-01,1.614733e+00,-24.982986
25%,6.885482e+01,7.379765e+01,1.502711
50%,9.518769e+01,9.630123e+01,4.332892
75%,1.108227e+02,1.092257e+02,8.976548
max,2.890921e+12,2.097637e+12,371537.500000

In [58]:
faostat_cpi_cm

                     fao_cpi_consumer_prices_food_indices  \
month_id country_id
1        1                                            NaN
         2                                            NaN
         3                                            NaN
         4                                            NaN
         5                                            NaN
...                                                   ...
852      242                                          NaN
         243                                          NaN
         244                                          NaN
         245                                          NaN
         246                                          NaN

                     fao_cpi_consumer_prices_general_indices  \
month_id country_id
1        1                                               NaN
         2                                               NaN
         3                                               NaN
         4                                               NaN
         5                                               NaN
...                                                      ...
852      242                                             NaN
         243                                             NaN
         244                                             NaN
         245                                             NaN
         246                                             NaN

                     fao_cpi_food_price_inflation
month_id country_id
1        1                                    NaN
         2                                    NaN
         3                                    NaN
         4                                    NaN
         5                                    NaN
...                                           ...
852      242                                  NaN
         243                                  NaN
         244                                  NaN
         245                                  NaN
         246                                  NaN

[158230 rows x 3 columns]

In [59]:
# Merge identifier df with data df

cols = ["country_id", "month_id"]

faostat_cpi_cm_cm_w_identifiers = pd.merge(identifiers_cm, faostat_cpi_cm, on=cols, how="left")

faostat_cpi_cm_cm_w_identifiers

,,year,month,isoab,country,fao_cpi_consumer_prices_food_indices,fao_cpi_consumer_prices_general_indices,fao_cpi_food_price_inflation
country_id,month_id,,,,,,,
1,1,1980,1,GUY,Guyana,NaN,NaN,NaN
2,1,1980,1,SUR,Suriname,NaN,NaN,NaN
3,1,1980,1,TTO,Trinidad and Tobago,NaN,NaN,NaN
4,1,1980,1,VEN,Venezuela,NaN,NaN,NaN
5,1,1980,1,WSM,Samoa,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
242,852,2050,12,TZA,Tanzania,NaN,NaN,NaN
243,852,2050,12,MAR,Morocco,NaN,NaN,NaN
244,852,2050,12,MRT,Mauritania,NaN,NaN,NaN
245,852,2050,12,SDN,Sudan,NaN,NaN,NaN
246,852,2050,12,SSD,South Sudan,NaN,NaN,NaN

In [60]:
# Query the data

faostat_cpi = faostat_cpi_cm_cm_w_identifiers.query(f'month_id >= {StartOfHistory} & month_id <= {EndOfHistory} & country_id == {country_id}')

faostat_cpi # displays the subset

                     year  month isoab country  \
country_id month_id
66         520       2023      4   SWE  Sweden
           521       2023      5   SWE  Sweden
           522       2023      6   SWE  Sweden
           523       2023      7   SWE  Sweden
           524       2023      8   SWE  Sweden
           525       2023      9   SWE  Sweden
           526       2023     10   SWE  Sweden
           527       2023     11   SWE  Sweden
           528       2023     12   SWE  Sweden
           529       2024      1   SWE  Sweden
           530       2024      2   SWE  Sweden
           531       2024      3   SWE  Sweden
           532       2024      4   SWE  Sweden
           533       2024      5   SWE  Sweden
           534       2024      6   SWE  Sweden
           535       2024      7   SWE  Sweden
           536       2024      8   SWE  Sweden
           537       2024      9   SWE  Sweden
           538       2024     10   SWE  Sweden
           539       2024     11   SWE  Sweden
           540       2024     12   SWE  Sweden
           541       2025      1   SWE  Sweden
           542       2025      2   SWE  Sweden
           543       2025      3   SWE  Sweden
           544       2025      4   SWE  Sweden
           545       2025      5   SWE  Sweden
           546       2025      6   SWE  Sweden
           547       2025      7   SWE  Sweden
           548       2025      8   SWE  Sweden
           549       2025      9   SWE  Sweden
           550       2025     10   SWE  Sweden
           551       2025     11   SWE  Sweden
           552       2025     12   SWE  Sweden
           553       2026      1   SWE  Sweden
           554       2026      2   SWE  Sweden
           555       2026      3   SWE  Sweden
           556       2026      4   SWE  Sweden
           557       2026      5   SWE  Sweden
           558       2026      6   SWE  Sweden
           559       2026      7   SWE  Sweden
           560       2026      8   SWE  Sweden
           561       2026      9   SWE  Sweden

                     fao_cpi_consumer_prices_food_indices  \
country_id month_id
66         520                                 138.770566
           521                                 138.227685
           522                                 138.624667
           523                                 140.504393
           524                                 139.462740
           525                                 139.272731
           526                                 139.788468
           527                                 140.015800
           528                                 139.778289
           529                                 140.239738
           530                                 140.409389
           531                                 139.493277
           532                                 139.683285
           533                                 140.243131
           534                                 140.120983
           535                                 142.027853
           536                                 141.389967
           537                                 142.211075
           538                                 142.228040
           539                                 142.679310
           540                                 142.197503
           541                                 143.289268
           542                                 145.893685
           543                                 146.996623
           544                                 147.367359
           545                                 147.552727
           546                                 147.552727
           547                                 149.201492
           548                                 148.095366
           549                                 146.951916
           550                                 147.518551
           551                                 147.089307
           552                                 147.460043
           553                                 147.556470
           554                                 148.187858
           555                                 146.725696
           556                                        NaN
           557                                        NaN
           558                                        NaN
           559                                        NaN
           560                                        NaN
           561                                        NaN

                     fao_cpi_consumer_prices_general_indices  \
country_id month_id
66         520                                    127.632706
           521                                    128.034819
           522                                    129.407111
           523                                    129.464556
           524                                    129.560297
           525                                    130.224103
           526                                    130.549624
           527                                    130.958120
           528                                    131.912341
           529                                    131.720859
           530                                    132.046379
           531                                    132.205948
           532                                    132.601679
           533                                    132.818692
           534                                    132.716568
           535                                    132.831458
           536                                    132.052762
           537                                    132.304881
           538                                    132.604870
           539                                    133.000601
           540                                    132.987835
           541                                    132.943156
           542                                    133.744191
           543                                    132.825075
           544                                    132.981452
           545                                    133.064428
           546                                    133.699512
           547                                    133.958014
           548                                    133.441011
           549                                    133.482498
           550                                    133.830358
           551                                    133.345269
           552                                    133.386757
           553                                    133.559464
           554                                    134.406406
           555                                    133.559464
           556                                           NaN
           557                                           NaN
           558                                           NaN
           559                                           NaN
           560                                           NaN
           561                                           NaN

                     fao_cpi_food_price_inflation
country_id month_id
66         520                          16.860964
           521                          14.162813
           522                          12.544764
           523                          10.532778
           524                           9.020741
           525                           7.669910
           526                           6.625430
           527                           6.218790
           528                           5.287909
           529                           3.815337
           530                           1.173537
           531                          -0.714838
           532                           0.657718
           533                           1.458062
           534                           1.079401
           535                           1.084279
           536                           1.381894
           537                           2.109776
           538                           1.745188
           539                           1.902292
           540                           1.730751
           541                           2.174512
           542                           3.905933
           543                           5.379002
           544                           5.501069
           545                           5.212088
           546                           5.303805
           547                           5.050868
           548                           4.742485
           549                           3.333665
           550                           3.719739
           551                           3.090846
           552                           3.700866
           553                           2.978033
           554                           1.572496
           555                          -0.184308
           556                                NaN
           557                                NaN
           558                                NaN
           559                                NaN
           560                                NaN
           561                                NaN

In [61]:
# Query the data

faostat_cpi = faostat_cpi_cm_cm_w_identifiers.query(f'month_id >= {StartOfHistory} & month_id <= {EndOfHistory} & country_id == {country_id}')

faostat_cpi # displays the subset

                     year  month isoab country  \
country_id month_id
66         520       2023      4   SWE  Sweden
           521       2023      5   SWE  Sweden
           522       2023      6   SWE  Sweden
           523       2023      7   SWE  Sweden
           524       2023      8   SWE  Sweden
           525       2023      9   SWE  Sweden
           526       2023     10   SWE  Sweden
           527       2023     11   SWE  Sweden
           528       2023     12   SWE  Sweden
           529       2024      1   SWE  Sweden
           530       2024      2   SWE  Sweden
           531       2024      3   SWE  Sweden
           532       2024      4   SWE  Sweden
           533       2024      5   SWE  Sweden
           534       2024      6   SWE  Sweden
           535       2024      7   SWE  Sweden
           536       2024      8   SWE  Sweden
           537       2024      9   SWE  Sweden
           538       2024     10   SWE  Sweden
           539       2024     11   SWE  Sweden
           540       2024     12   SWE  Sweden
           541       2025      1   SWE  Sweden
           542       2025      2   SWE  Sweden
           543       2025      3   SWE  Sweden
           544       2025      4   SWE  Sweden
           545       2025      5   SWE  Sweden
           546       2025      6   SWE  Sweden
           547       2025      7   SWE  Sweden
           548       2025      8   SWE  Sweden
           549       2025      9   SWE  Sweden
           550       2025     10   SWE  Sweden
           551       2025     11   SWE  Sweden
           552       2025     12   SWE  Sweden
           553       2026      1   SWE  Sweden
           554       2026      2   SWE  Sweden
           555       2026      3   SWE  Sweden
           556       2026      4   SWE  Sweden
           557       2026      5   SWE  Sweden
           558       2026      6   SWE  Sweden
           559       2026      7   SWE  Sweden
           560       2026      8   SWE  Sweden
           561       2026      9   SWE  Sweden

                     fao_cpi_consumer_prices_food_indices  \
country_id month_id
66         520                                 138.770566
           521                                 138.227685
           522                                 138.624667
           523                                 140.504393
           524                                 139.462740
           525                                 139.272731
           526                                 139.788468
           527                                 140.015800
           528                                 139.778289
           529                                 140.239738
           530                                 140.409389
           531                                 139.493277
           532                                 139.683285
           533                                 140.243131
           534                                 140.120983
           535                                 142.027853
           536                                 141.389967
           537                                 142.211075
           538                                 142.228040
           539                                 142.679310
           540                                 142.197503
           541                                 143.289268
           542                                 145.893685
           543                                 146.996623
           544                                 147.367359
           545                                 147.552727
           546                                 147.552727
           547                                 149.201492
           548                                 148.095366
           549                                 146.951916
           550                                 147.518551
           551                                 147.089307
           552                                 147.460043
           553                                 147.556470
           554                                 148.187858
           555                                 146.725696
           556                                        NaN
           557                                        NaN
           558                                        NaN
           559                                        NaN
           560                                        NaN
           561                                        NaN

                     fao_cpi_consumer_prices_general_indices  \
country_id month_id
66         520                                    127.632706
           521                                    128.034819
           522                                    129.407111
           523                                    129.464556
           524                                    129.560297
           525                                    130.224103
           526                                    130.549624
           527                                    130.958120
           528                                    131.912341
           529                                    131.720859
           530                                    132.046379
           531                                    132.205948
           532                                    132.601679
           533                                    132.818692
           534                                    132.716568
           535                                    132.831458
           536                                    132.052762
           537                                    132.304881
           538                                    132.604870
           539                                    133.000601
           540                                    132.987835
           541                                    132.943156
           542                                    133.744191
           543                                    132.825075
           544                                    132.981452
           545                                    133.064428
           546                                    133.699512
           547                                    133.958014
           548                                    133.441011
           549                                    133.482498
           550                                    133.830358
           551                                    133.345269
           552                                    133.386757
           553                                    133.559464
           554                                    134.406406
           555                                    133.559464
           556                                           NaN
           557                                           NaN
           558                                           NaN
           559                                           NaN
           560                                           NaN
           561                                           NaN

                     fao_cpi_food_price_inflation
country_id month_id
66         520                          16.860964
           521                          14.162813
           522                          12.544764
           523                          10.532778
           524                           9.020741
           525                           7.669910
           526                           6.625430
           527                           6.218790
           528                           5.287909
           529                           3.815337
           530                           1.173537
           531                          -0.714838
           532                           0.657718
           533                           1.458062
           534                           1.079401
           535                           1.084279
           536                           1.381894
           537                           2.109776
           538                           1.745188
           539                           1.902292
           540                           1.730751
           541                           2.174512
           542                           3.905933
           543                           5.379002
           544                           5.501069
           545                           5.212088
           546                           5.303805
           547                           5.050868
           548                           4.742485
           549                           3.333665
           550                           3.719739
           551                           3.090846
           552                           3.700866
           553                           2.978033
           554                           1.572496
           555                          -0.184308
           556                                NaN
           557                                NaN
           558                                NaN
           559                                NaN
           560                                NaN
           561                                NaN

# FAOSTAT FSEC

In [62]:
faostat_fsec_cm = (Queryset("fatalities002_faostat_fsec_cm", "country_year")

# FAOSTAT FSEC

.with_column(Column("fao_fsec_gdp_pc_ppp", from_loa = "country_year", from_column = "gdp_pc_ppp")) # not updated
.with_column(Column("fao_fsec_pol_stability", from_loa = "country_year", from_column = "pol_stability"))                   
.with_column(Column("fao_fsec_pcap_fprod_var", from_loa = "country_year", from_column = "pcap_fprod_var")) # not updated                  
.with_column(Column("fao_fsec_pcap_fsupply_var", from_loa = "country_year", from_column = "pcap_fsupply_var"))                   
.with_column(Column("fao_fsec_pct_pop_basicdrink", from_loa = "country_year", from_column = "pct_pop_basicdrink"))                   
.with_column(Column("fao_fsec_pct_pop_basicsani", from_loa = "country_year", from_column = "pct_pop_basicsani"))                   
.with_column(Column("fao_fsec_pct_und5_wasting", from_loa = "country_year", from_column = "pct_und5_wasting"))                   
.with_column(Column("fao_fsec_pct_und5_stunted", from_loa = "country_year", from_column = "pct_und5_stunted"))                   
.with_column(Column("fao_fsec_pct_und5_overweight", from_loa = "country_year", from_column = "pct_und5_overweight"))                   
.with_column(Column("fao_fsec_prev_adult_obesity", from_loa = "country_year", from_column = "prev_adult_obesity"))                   
.with_column(Column("fao_fsec_prev_repr_anemia", from_loa = "country_year", from_column = "prev_repr_anemia"))                   
.with_column(Column("fao_fsec_prev_infant_bfeed", from_loa = "country_year", from_column = "prev_infant_bfeed"))                   
.with_column(Column("fao_fsec_rail_density", from_loa = "country_year", from_column = "rail_density"))                   
.with_column(Column("fao_fsec_pct_pop_safedrink", from_loa = "country_year", from_column = "pct_pop_safedrink"))                   
.with_column(Column("fao_fsec_pct_pop_safesani", from_loa = "country_year", from_column = "pct_pop_safesani"))                   
.with_column(Column("fao_fsec_prev_lowbweight", from_loa = "country_year", from_column = "prev_lowbweight"))                   
.with_column(Column("fao_fsec_avg_adequate_diet", from_loa = "country_year", from_column = "avg_adequate_diet"))                   
.with_column(Column("fao_fsec_avg_fprod_value", from_loa = "country_year", from_column = "avg_fprod_value"))  # not updated                 
.with_column(Column("fao_fsec_kcal_pcap_day", from_loa = "country_year", from_column = "kcal_pcap_day"))    # not updated               
.with_column(Column("fao_fsec_kcal_pcap_day_cerotu", from_loa = "country_year", from_column = "kcal_pcap_day_cerotu"))           # not updated        
.with_column(Column("fao_fsec_avg_protein_pcap_day", from_loa = "country_year", from_column = "avg_protein_pcap_day"))                   
.with_column(Column("fao_fsec_avg_animalprotein_pcap_day", from_loa = "country_year", from_column = "avg_animalprotein_pcap_day"))                   
.with_column(Column("fao_fsec_pop_undernourished", from_loa = "country_year", from_column = "pop_undernourished"))                   
.with_column(Column("fao_fsec_pct_cereal_import", from_loa = "country_year", from_column = "pct_cereal_import"))                   
.with_column(Column("fao_fsec_pct_arable_land", from_loa = "country_year", from_column = "pct_arable_land"))                    
.with_column(Column("fao_fsec_pct_fimport_merch", from_loa = "country_year", from_column = "pct_fimport_merch"))                   
.with_column(Column("fao_fsec_pct_severe_finsecurity", from_loa = "country_year", from_column = "pct_severe_finsecurity"))                   
.with_column(Column("fao_fsec_pct_modsevere_finsecurity", from_loa = "country_year", from_column = "pct_modsevere_finsecurity"))                   
.with_column(Column("fao_fsec_pop_severe_finsecurity", from_loa = "country_year", from_column = "pop_severe_finsecurity"))                   
.with_column(Column("fao_fsec_pop_modsevere_finsecurity", from_loa = "country_year", from_column = "pop_modsevere_finsecurity"))                   
.with_column(Column("fao_fsec_avg_energy_req", from_loa = "country_year", from_column = "avg_energy_req"))                   
.with_column(Column("fao_fsec_avg_fatsupply", from_loa = "country_year", from_column = "avg_fatsupply"))                   
.with_column(Column("fao_fsec_hcc_coeff_dist", from_loa = "country_year", from_column = "hcc_coeff_dist"))                   
.with_column(Column("fao_fsec_caloric_loss_retail", from_loa = "country_year", from_column = "caloric_loss_retail"))      
.with_column(Column("fao_fsec_min_energy_req", from_loa = "country_year", from_column = "min_energy_req"))                  
)
      
faostat_fsec_cm = faostat_fsec_cm.publish().fetch()

print(f"A dataset with {len(faostat_fsec_cm.columns)} columns, with "
      f"data between t {min(faostat_fsec_cm.index.get_level_values(0))} "
      f"and {max(faostat_fsec_cm.index.get_level_values(0))}. "
      f"({len(np.unique(faostat_fsec_cm.index.get_level_values(1)))} units)"
     )

Queryset fatalities002_faostat_fsec_cm read successfully
A dataset with 35 columns, with data between t 1900 and 2050. (220 units)

In [63]:
faostat_fsec_cm.describe()

,fao_fsec_gdp_pc_ppp,fao_fsec_pol_stability,fao_fsec_pcap_fprod_var,fao_fsec_pcap_fsupply_var,fao_fsec_pct_pop_basicdrink,fao_fsec_pct_pop_basicsani,fao_fsec_pct_und5_wasting,fao_fsec_pct_und5_stunted,fao_fsec_pct_und5_overweight,fao_fsec_prev_adult_obesity,...,fao_fsec_pct_fimport_merch,fao_fsec_pct_severe_finsecurity,fao_fsec_pct_modsevere_finsecurity,fao_fsec_pop_severe_finsecurity,fao_fsec_pop_modsevere_finsecurity,fao_fsec_avg_energy_req,fao_fsec_avg_fatsupply,fao_fsec_hcc_coeff_dist,fao_fsec_caloric_loss_retail,fao_fsec_min_energy_req
count,4074.000000,3991.000000,4074.000000,3629.000000,4513.000000,4485.000000,912.000000,3900.000000,3925.000000,4598.000000,...,4152.000000,4074.000000,4310.000000,4074.000000,4074.000000,4678.000000,3576.000000,3817.000000,4782.000000,4797.000000
mean,16544.019710,-0.081040,9.537776,36.328465,85.564591,72.021851,5.349013,20.270744,6.740994,18.895824,...,61.462187,1.616846,7.903109,0.410898,1.428598,2349.544036,87.322791,0.256361,2.847242,1745.326454
std,19285.848438,0.989495,12.554413,26.172518,17.963810,29.940060,4.413643,14.372792,4.374624,11.910332,...,409.713731,6.190713,17.515641,1.970131,6.604933,132.338171,35.985062,0.048713,0.756483,374.767778
min,0.000000,-3.310000,0.000000,1.000000,19.000000,3.000000,0.100000,0.900000,0.600000,0.300000,...,1.000000,0.000000,0.000000,0.000000,0.000000,2017.000000,17.700000,0.170000,1.500000,0.000000
25%,2875.275000,-0.720000,1.100000,20.000000,77.000000,46.000000,1.600000,7.800000,3.500000,10.125000,...,7.000000,0.000000,0.000000,0.000000,0.000000,2238.250000,57.700000,0.210000,2.280000,1730.000000
50%,9735.800000,0.010000,5.900000,30.000000,94.000000,86.000000,4.300000,17.700000,5.800000,18.100000,...,14.500000,0.000000,0.000000,0.000000,0.000000,2344.000000,83.000000,0.250000,2.790000,1815.000000
75%,23126.400000,0.770000,12.700000,46.000000,99.000000,98.000000,8.100000,30.700000,9.100000,24.900000,...,39.000000,0.000000,5.400000,0.000000,0.000000,2466.000000,113.850000,0.290000,3.130000,1905.000000
max,114889.000000,1.760000,107.700000,289.000000,100.000000,100.000000,21.300000,63.000000,28.700000,73.800000,...,20840.000000,65.400000,89.800000,43.000000,116.000000,2702.000000,186.000000,0.400000,7.010000,2077.000000

In [64]:
# Fix discrepancies in column names

faostat_fsec_cm = (
    faostat_fsec_cm
    .reset_index()
    .rename(columns={'year_id': 'year'})
    .set_index(['year', 'country_id'])
)

In [65]:
faostat_fsec_cm

                 fao_fsec_gdp_pc_ppp  fao_fsec_pol_stability  \
year country_id
1900 4                           NaN                     NaN
     7                           NaN                     NaN
     8                           NaN                     NaN
     10                          NaN                     NaN
     11                          NaN                     NaN
...                              ...                     ...
2050 242                         NaN                     NaN
     243                         NaN                     NaN
     244                         NaN                     NaN
     245                         NaN                     NaN
     246                         NaN                     NaN

                 fao_fsec_pcap_fprod_var  fao_fsec_pcap_fsupply_var  \
year country_id
1900 4                               NaN                        NaN
     7                               NaN                        NaN
     8                               NaN                        NaN
     10                              NaN                        NaN
     11                              NaN                        NaN
...                                  ...                        ...
2050 242                             NaN                        NaN
     243                             NaN                        NaN
     244                             NaN                        NaN
     245                             NaN                        NaN
     246                             NaN                        NaN

                 fao_fsec_pct_pop_basicdrink  fao_fsec_pct_pop_basicsani  \
year country_id
1900 4                                   NaN                         NaN
     7                                   NaN                         NaN
     8                                   NaN                         NaN
     10                                  NaN                         NaN
     11                                  NaN                         NaN
...                                      ...                         ...
2050 242                                 NaN                         NaN
     243                                 NaN                         NaN
     244                                 NaN                         NaN
     245                                 NaN                         NaN
     246                                 NaN                         NaN

                 fao_fsec_pct_und5_wasting  fao_fsec_pct_und5_stunted  \
year country_id
1900 4                                 NaN                        NaN
     7                                 NaN                        NaN
     8                                 NaN                        NaN
     10                                NaN                        NaN
     11                                NaN                        NaN
...                                    ...                        ...
2050 242                               NaN                        NaN
     243                               NaN                        NaN
     244                               NaN                        NaN
     245                               NaN                        NaN
     246                               NaN                        NaN

                 fao_fsec_pct_und5_overweight  fao_fsec_prev_adult_obesity  \
year country_id
1900 4                                    NaN                          NaN
     7                                    NaN                          NaN
     8                                    NaN                          NaN
     10                                   NaN                          NaN
     11                                   NaN                          NaN
...                                       ...                          ...
2050 242                                  NaN                          NaN
     243                                  NaN                          NaN
     244                                  NaN                          NaN
     245                                  NaN                          NaN
     246                                  NaN                          NaN

                 ...  fao_fsec_pct_fimport_merch  \
year country_id  ...
1900 4           ...                         NaN
     7           ...                         NaN
     8           ...                         NaN
     10          ...                         NaN
     11          ...                         NaN
...              ...                         ...
2050 242         ...                         NaN
     243         ...                         NaN
     244         ...                         NaN
     245         ...                         NaN
     246         ...                         NaN

                 fao_fsec_pct_severe_finsecurity  \
year country_id
1900 4                                       NaN
     7                                       NaN
     8                                       NaN
     10                                      NaN
     11                                      NaN
...                                          ...
2050 242                                     NaN
     243                                     NaN
     244                                     NaN
     245                                     NaN
     246                                     NaN

                 fao_fsec_pct_modsevere_finsecurity  \
year country_id
1900 4                                          NaN
     7                                          NaN
     8                                          NaN
     10                                         NaN
     11                                         NaN
...                                             ...
2050 242                                        NaN
     243                                        NaN
     244                                        NaN
     245                                        NaN
     246                                        NaN

                 fao_fsec_pop_severe_finsecurity  \
year country_id
1900 4                                       NaN
     7                                       NaN
     8                                       NaN
     10                                      NaN
     11                                      NaN
...                                          ...
2050 242                                     NaN
     243                                     NaN
     244                                     NaN
     245                                     NaN
     246                                     NaN

                 fao_fsec_pop_modsevere_finsecurity  fao_fsec_avg_energy_req  \
year country_id
1900 4                                          NaN                      NaN
     7                                          NaN                      NaN
     8                                          NaN                      NaN
     10                                         NaN                      NaN
     11                                         NaN                      NaN
...                                             ...                      ...
2050 242                                        NaN                      NaN
     243                                        NaN                      NaN
     244                                        NaN                      NaN
     245                                        NaN                      NaN
     246                                        NaN                      NaN

                 fao_fsec_avg_fatsupply  fao_fsec_hcc_coeff_dist  \
year country_id
1900 4                              NaN                      NaN
     7                              NaN                      NaN
     8                              NaN                      NaN
     10                             NaN                      NaN
     11                             NaN                      NaN
...                                 ...                      ...
2050 242                            NaN                      NaN
     243                            NaN                      NaN
     244                            NaN                      NaN
     245                            NaN                      NaN
     246                            NaN                      NaN

                 fao_fsec_caloric_loss_retail  fao_fsec_min_energy_req
year country_id
1900 4                                    NaN                      NaN
     7                                    NaN                      NaN
     8                                    NaN                      NaN
     10                                   NaN                      NaN
     11                                   NaN                      NaN
...                                       ...                      ...
2050 242                                  NaN                      NaN
     243                                  NaN                      NaN
     244                                  NaN                      NaN
     245                                  NaN                      NaN
     246                                  NaN                      NaN

[20392 rows x 35 columns]

In [66]:
# Merge identifier df with data df

cols = ["country_id", "year"]

faostat_fsec_cm_w_identifiers = pd.merge(identifiers_cm, faostat_fsec_cm, on=cols, how="left")

faostat_fsec_cm_w_identifiers

,year,month,isoab,country,fao_fsec_gdp_pc_ppp,fao_fsec_pol_stability,fao_fsec_pcap_fprod_var,fao_fsec_pcap_fsupply_var,fao_fsec_pct_pop_basicdrink,fao_fsec_pct_pop_basicsani,...,fao_fsec_pct_fimport_merch,fao_fsec_pct_severe_finsecurity,fao_fsec_pct_modsevere_finsecurity,fao_fsec_pop_severe_finsecurity,fao_fsec_pop_modsevere_finsecurity,fao_fsec_avg_energy_req,fao_fsec_avg_fatsupply,fao_fsec_hcc_coeff_dist,fao_fsec_caloric_loss_retail,fao_fsec_min_energy_req
country_id,,,,,,,,,,,,,,,,,,,,,
1,1980,1,GUY,Guyana,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1980,1,SUR,Suriname,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1980,1,TTO,Trinidad and Tobago,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1980,1,VEN,Venezuela,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1980,1,WSM,Samoa,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,2050,12,TZA,Tanzania,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243,2050,12,MAR,Morocco,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,2050,12,MRT,Mauritania,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,2050,12,SDN,Sudan,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246,2050,12,SSD,South Sudan,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
# Query the data

faostat_fsec_cm = faostat_fsec_cm.query(f'year >= {StartYear} & year <= {EndYear} & country_id == {country_id}')

faostat_fsec_cm # displays the subset

,,fao_fsec_gdp_pc_ppp,fao_fsec_pol_stability,fao_fsec_pcap_fprod_var,fao_fsec_pcap_fsupply_var,fao_fsec_pct_pop_basicdrink,fao_fsec_pct_pop_basicsani,fao_fsec_pct_und5_wasting,fao_fsec_pct_und5_stunted,fao_fsec_pct_und5_overweight,fao_fsec_prev_adult_obesity,...,fao_fsec_pct_fimport_merch,fao_fsec_pct_severe_finsecurity,fao_fsec_pct_modsevere_finsecurity,fao_fsec_pop_severe_finsecurity,fao_fsec_pop_modsevere_finsecurity,fao_fsec_avg_energy_req,fao_fsec_avg_fatsupply,fao_fsec_hcc_coeff_dist,fao_fsec_caloric_loss_retail,fao_fsec_min_energy_req
year,country_id,,,,,,,,,,,,,,,,,,,,,
2010,66,47791.4,1.09,5.8,18.0,100.0,99.0,NaN,NaN,NaN,14.8,...,6.0,0.0,0.0,0.00,0.0,2542.0,132.2,0.20,1.96,1947.0
2011,66,48947.4,1.23,2.6,40.0,100.0,99.0,NaN,NaN,NaN,14.9,...,6.0,0.0,0.0,0.00,0.0,2540.0,135.6,0.20,1.94,1946.0
2012,66,48300.8,1.17,2.0,48.0,100.0,99.0,NaN,NaN,NaN,15.0,...,6.0,0.0,0.0,0.00,0.0,2538.0,135.5,0.20,1.92,1944.0
2013,66,48462.2,1.13,2.4,41.0,100.0,99.0,NaN,NaN,NaN,15.2,...,7.0,0.0,0.0,0.00,0.0,2536.0,136.2,0.20,1.95,1943.0
2014,66,49259.0,1.07,2.4,35.0,100.0,99.0,NaN,NaN,NaN,15.3,...,7.0,0.8,4.5,0.09,0.4,2535.0,136.7,0.20,1.92,1942.0
2015,66,50929.0,0.93,8.0,8.0,100.0,99.0,NaN,NaN,NaN,15.5,...,7.0,0.8,4.5,0.09,0.4,2534.0,139.0,0.20,1.91,1940.0
2016,66,51334.4,1.00,11.9,15.0,100.0,99.0,NaN,NaN,NaN,15.6,...,7.0,0.8,4.5,0.09,0.4,2533.0,138.2,0.20,1.91,1941.0
2017,66,51948.0,0.97,11.4,24.0,100.0,99.0,NaN,NaN,NaN,15.8,...,7.0,1.0,5.3,0.09,0.5,2533.0,136.2,0.20,1.91,1940.0
2018,66,52349.3,0.92,0.0,37.0,100.0,99.0,NaN,NaN,NaN,16.0,...,7.0,1.0,5.7,0.10,0.5,2533.0,133.6,0.20,1.90,1947.0
2019,66,52531.2,1.01,0.0,55.0,100.0,99.0,NaN,NaN,NaN,16.3,...,7.0,1.2,5.3,0.10,0.6,2533.0,133.8,0.20,1.93,1948.0
2020,66,50683.3,1.00,0.0,40.0,100.0,99.0,NaN,NaN,NaN,16.5,...,7.0,1.2,5.3,0.10,0.5,2535.0,135.5,0.21,1.90,1949.0
2021,66,NaN,1.01,NaN,32.0,100.0,99.0,NaN,NaN,NaN,16.7,...,7.0,NaN,5.4,NaN,NaN,2536.0,137.4,0.20,1.88,1950.0
2022,66,NaN,0.91,NaN,30.0,100.0,99.0,NaN,NaN,NaN,17.0,...,7.0,NaN,6.0,NaN,NaN,2538.0,140.8,0.20,1.88,1951.0
2023,66,NaN,NaN,NaN,34.0,100.0,99.0,NaN,NaN,NaN,17.2,...,7.0,NaN,6.9,NaN,NaN,2541.0,NaN,0.21,1.84,1954.0
2024,66,NaN,NaN,NaN,20.0,100.0,99.0,NaN,NaN,NaN,17.5,...,NaN,NaN,NaN,NaN,NaN,2544.0,NaN,0.21,1.84,1956.0
2025,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2547.0,NaN,NaN,1.84,NaN
2026,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# FAOSTAT PP

In [68]:
faostat_pp_cm = (Queryset("fatalities002_faostat_pp_cm", "country_month")

# FAOSTAT FSEC

.with_column(Column("fao_pp_meat_price", from_loa = "country_month", from_column = "meat_price")) 
.with_column(Column("fao_pp_milk_price", from_loa = "country_month", from_column = "milk_price"))                   
.with_column(Column("fao_pp_mp_price", from_loa = "country_month", from_column = "mp_price"))                  
.with_column(Column("fao_pp_sugar_price", from_loa = "country_month", from_column = "sugar_price"))                   
.with_column(Column("fao_pp_wheat_price", from_loa = "country_month", from_column = "wheat_price"))                   
)
       
faostat_pp_cm = faostat_pp_cm.publish().fetch()

print(f"A dataset with {len(faostat_pp_cm.columns)} columns, with "
      f"data between t {min(faostat_pp_cm.index.get_level_values(0))} "
      f"and {max(faostat_pp_cm.index.get_level_values(0))}. "
      f"({len(np.unique(faostat_pp_cm.index.get_level_values(1)))} units)"
     )

Queryset fatalities002_faostat_pp_cm read successfully
A dataset with 5 columns, with data between t 1 and 852. (213 units)

In [69]:
faostat_pp_cm.describe()

,fao_pp_meat_price,fao_pp_milk_price,fao_pp_mp_price,fao_pp_sugar_price,fao_pp_wheat_price
count,1.381000e+04,1.448000e+04,1.915100e+04,8.383000e+03,1.099600e+04
mean,2.832964e+06,3.309524e+05,1.146956e+06,1.429073e+05,1.246365e+05
std,7.763138e+07,9.542470e+06,2.311139e+07,1.983387e+06,1.031629e+06
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,0.000000e+00,0.000000e+00,7.117440e+02,0.000000e+00,0.000000e+00
50%,4.158708e+03,7.533750e+02,4.494400e+03,2.900000e+01,2.283500e+02
75%,9.448431e+04,1.827000e+04,1.093801e+05,1.315800e+03,3.971075e+03
max,5.848028e+09,6.906592e+08,1.967628e+09,1.083760e+08,8.496700e+07

In [70]:
faostat_pp_cm

                     fao_pp_meat_price  fao_pp_milk_price  fao_pp_mp_price  \
month_id country_id
1        1                         NaN                NaN              NaN
         2                         NaN                NaN              NaN
         3                         NaN                NaN              NaN
         4                         NaN                NaN              NaN
         5                         NaN                NaN              NaN
...                                ...                ...              ...
852      242                       NaN                NaN              NaN
         243                       NaN                NaN              NaN
         244                       NaN                NaN              NaN
         245                       NaN                NaN              NaN
         246                       NaN                NaN              NaN

                     fao_pp_sugar_price  fao_pp_wheat_price
month_id country_id
1        1                          NaN                 NaN
         2                          NaN                 NaN
         3                          NaN                 NaN
         4                          NaN                 NaN
         5                          NaN                 NaN
...                                 ...                 ...
852      242                        NaN                 NaN
         243                        NaN                 NaN
         244                        NaN                 NaN
         245                        NaN                 NaN
         246                        NaN                 NaN

[158230 rows x 5 columns]

In [71]:
# Merge identifier df with data df

cols = ["country_id", "month_id"]

faostat_pp_cm_cm_w_identifiers = pd.merge(identifiers_cm, faostat_pp_cm, on=cols, how="left")

faostat_pp_cm_cm_w_identifiers

,,year,month,isoab,country,fao_pp_meat_price,fao_pp_milk_price,fao_pp_mp_price,fao_pp_sugar_price,fao_pp_wheat_price
country_id,month_id,,,,,,,,,
1,1,1980,1,GUY,Guyana,NaN,NaN,NaN,NaN,NaN
2,1,1980,1,SUR,Suriname,NaN,NaN,NaN,NaN,NaN
3,1,1980,1,TTO,Trinidad and Tobago,NaN,NaN,NaN,NaN,NaN
4,1,1980,1,VEN,Venezuela,NaN,NaN,NaN,NaN,NaN
5,1,1980,1,WSM,Samoa,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
242,852,2050,12,TZA,Tanzania,NaN,NaN,NaN,NaN,NaN
243,852,2050,12,MAR,Morocco,NaN,NaN,NaN,NaN,NaN
244,852,2050,12,MRT,Mauritania,NaN,NaN,NaN,NaN,NaN
245,852,2050,12,SDN,Sudan,NaN,NaN,NaN,NaN,NaN
246,852,2050,12,SSD,South Sudan,NaN,NaN,NaN,NaN,NaN

In [72]:
# Query the data

faostat_pp_cm = faostat_pp_cm_cm_w_identifiers.query(f'month_id >= {StartOfHistory} & month_id <= {EndOfHistory} & country_id == {country_id}')

faostat_pp_cm # displays the subset

                     year  month isoab country  fao_pp_meat_price  \
country_id month_id
66         520       2023      4   SWE  Sweden                NaN
           521       2023      5   SWE  Sweden                NaN
           522       2023      6   SWE  Sweden                NaN
           523       2023      7   SWE  Sweden                NaN
           524       2023      8   SWE  Sweden                NaN
           525       2023      9   SWE  Sweden                NaN
           526       2023     10   SWE  Sweden                NaN
           527       2023     11   SWE  Sweden                NaN
           528       2023     12   SWE  Sweden                NaN
           529       2024      1   SWE  Sweden                NaN
           530       2024      2   SWE  Sweden                NaN
           531       2024      3   SWE  Sweden                NaN
           532       2024      4   SWE  Sweden                NaN
           533       2024      5   SWE  Sweden                NaN
           534       2024      6   SWE  Sweden                NaN
           535       2024      7   SWE  Sweden                NaN
           536       2024      8   SWE  Sweden                NaN
           537       2024      9   SWE  Sweden                NaN
           538       2024     10   SWE  Sweden                NaN
           539       2024     11   SWE  Sweden                NaN
           540       2024     12   SWE  Sweden                NaN
           541       2025      1   SWE  Sweden                NaN
           542       2025      2   SWE  Sweden                NaN
           543       2025      3   SWE  Sweden                NaN
           544       2025      4   SWE  Sweden                NaN
           545       2025      5   SWE  Sweden                NaN
           546       2025      6   SWE  Sweden                NaN
           547       2025      7   SWE  Sweden                NaN
           548       2025      8   SWE  Sweden                NaN
           549       2025      9   SWE  Sweden                NaN
           550       2025     10   SWE  Sweden                NaN
           551       2025     11   SWE  Sweden                NaN
           552       2025     12   SWE  Sweden                NaN
           553       2026      1   SWE  Sweden                NaN
           554       2026      2   SWE  Sweden                NaN
           555       2026      3   SWE  Sweden                NaN
           556       2026      4   SWE  Sweden                NaN
           557       2026      5   SWE  Sweden                NaN
           558       2026      6   SWE  Sweden                NaN
           559       2026      7   SWE  Sweden                NaN
           560       2026      8   SWE  Sweden                NaN
           561       2026      9   SWE  Sweden                NaN

                     fao_pp_milk_price  fao_pp_mp_price  fao_pp_sugar_price  \
country_id month_id
66         520                  6047.0      4722.713333                 NaN
           521                  5547.0      4853.264286                 NaN
           522                  5057.0      5416.730769                 NaN
           523                  4587.0      8422.306250                 NaN
           524                  4597.0      7750.943750               408.8
           525                  4617.0      8123.988889               408.8
           526                  4647.0      4809.531250               408.8
           527                  4847.0      5079.080000               408.8
           528                  4897.0      5498.457143                 NaN
           529                  5307.0      5622.492857                 NaN
           530                  5247.0      5621.828571                 NaN
           531                  5357.0      5361.033333                 NaN
           532                  5377.0      5581.653846                 NaN
           533                  5327.0      6239.836364                 NaN
           534                  5257.0      6182.969231                 NaN
           535                  5377.0      9479.646154                 NaN
           536                  5457.0      7648.458824               416.6
           537                  5737.0      7678.188235               416.6
           538                  6247.0      5159.381250               416.6
           539                  6607.0      5387.760000               416.6
           540                  6697.0      5704.692857                 NaN
           541                  6717.0      5787.685714                 NaN
           542                     NaN              NaN                 NaN
           543                     NaN              NaN                 NaN
           544                     NaN              NaN                 NaN
           545                     NaN              NaN                 NaN
           546                     NaN              NaN                 NaN
           547                     NaN              NaN                 NaN
           548                     NaN              NaN                 NaN
           549                     NaN              NaN                 NaN
           550                     NaN              NaN                 NaN
           551                     NaN              NaN                 NaN
           552                     NaN              NaN                 NaN
           553                     NaN              NaN                 NaN
           554                     NaN              NaN                 NaN
           555                     NaN              NaN                 NaN
           556                     NaN              NaN                 NaN
           557                     NaN              NaN                 NaN
           558                     NaN              NaN                 NaN
           559                     NaN              NaN                 NaN
           560                     NaN              NaN                 NaN
           561                     NaN              NaN                 NaN

                     fao_pp_wheat_price
country_id month_id
66         520                   2432.0
           521                   2598.0
           522                   2605.0
           523                   2546.0
           524                   2738.0
           525                   2737.0
           526                   2618.0
           527                   2388.0
           528                   2323.0
           529                   2393.0
           530                   2435.0
           531                   2264.0
           532                   2250.0
           533                   2543.0
           534                   2283.0
           535                   2067.0
           536                   1955.0
           537                   2292.0
           538                   2350.0
           539                   2310.0
           540                   2358.0
           541                   2516.0
           542                      NaN
           543                      NaN
           544                      NaN
           545                      NaN
           546                      NaN
           547                      NaN
           548                      NaN
           549                      NaN
           550                      NaN
           551                      NaN
           552                      NaN
           553                      NaN
           554                      NaN
           555                      NaN
           556                      NaN
           557                      NaN
           558                      NaN
           559                      NaN
           560                      NaN
           561                      NaN

In [73]:
faostat_pp_cm_cm_w_identifiers.to_csv('faostat_pp_cm_cm_w_identifiers.csv')

In [74]:
print("All done!")

All done!

# IMF WEO

In [75]:
imf_weo_cm = (Queryset("fatalities002_imf_weo_cm", "country_month")

# FAOSTAT FSEC

.with_column(Column("imf_weo_ngdp_rpch", from_loa = "country_year", from_column = "imf_weo_ngdp_rpch")) 
.with_column(Column("imf_weo_ngdpd", from_loa = "country_year", from_column = "imf_weo_ngdpd"))                                    
)
       
imf_weo_cm = imf_weo_cm.publish().fetch()

print(f"A dataset with {len(imf_weo_cm.columns)} columns, with "
      f"data between t {min(imf_weo_cm.index.get_level_values(0))} "
      f"and {max(imf_weo_cm.index.get_level_values(0))}. "
      f"({len(np.unique(imf_weo_cm.index.get_level_values(1)))} units)"
     )

Queryset fatalities002_imf_weo_cm read successfully
A dataset with 2 columns, with data between t 1 and 852. (213 units)

In [76]:
imf_weo_cm.describe()

       imf_weo_ngdp_rpch  imf_weo_ngdpd
count       63444.000000   63650.000000
mean            3.148042     574.786540
std             4.693294    2235.495822
min           -42.200000       0.069000
25%             1.500000      13.684250
50%             3.200000      66.346000
75%             5.300000     327.869000
max            62.200000   39031.262000

In [77]:
imf_weo_cm

                     imf_weo_ngdp_rpch  imf_weo_ngdpd
month_id country_id
1        1                         NaN            NaN
         2                        -6.5          1.276
         3                        10.4          6.343
         4                        -4.9         69.841
         5                         NaN            NaN
...                                ...            ...
852      242                       NaN            NaN
         243                       NaN            NaN
         244                       NaN            NaN
         245                       NaN            NaN
         246                       NaN            NaN

[158230 rows x 2 columns]

In [78]:
# Merge identifier df with data df

cols = ["country_id", "month_id"]

imf_weo_cm_w_identifiers = pd.merge(identifiers_cm, imf_weo_cm, on=cols, how="left")

imf_weo_cm_w_identifiers

,,year,month,isoab,country,imf_weo_ngdp_rpch,imf_weo_ngdpd
country_id,month_id,,,,,,
1,1,1980,1,GUY,Guyana,NaN,NaN
2,1,1980,1,SUR,Suriname,-6.5,1.276
3,1,1980,1,TTO,Trinidad and Tobago,10.4,6.343
4,1,1980,1,VEN,Venezuela,-4.9,69.841
5,1,1980,1,WSM,Samoa,NaN,NaN
...,...,...,...,...,...,...,...
242,852,2050,12,TZA,Tanzania,NaN,NaN
243,852,2050,12,MAR,Morocco,NaN,NaN
244,852,2050,12,MRT,Mauritania,NaN,NaN
245,852,2050,12,SDN,Sudan,NaN,NaN
246,852,2050,12,SSD,South Sudan,NaN,NaN

In [79]:
# Query the data

imf_cm = imf_weo_cm_w_identifiers.query(f'month_id >= {StartOfHistory} & month_id <= {EndOfHistory} & country_id == {country_id}')

imf_cm # displays the subset

                     year  month isoab country  imf_weo_ngdp_rpch  \
country_id month_id
66         520       2023      4   SWE  Sweden               -0.2
           521       2023      5   SWE  Sweden               -0.2
           522       2023      6   SWE  Sweden               -0.2
           523       2023      7   SWE  Sweden               -0.2
           524       2023      8   SWE  Sweden               -0.2
           525       2023      9   SWE  Sweden               -0.2
           526       2023     10   SWE  Sweden               -0.2
           527       2023     11   SWE  Sweden               -0.2
           528       2023     12   SWE  Sweden               -0.2
           529       2024      1   SWE  Sweden                1.0
           530       2024      2   SWE  Sweden                1.0
           531       2024      3   SWE  Sweden                1.0
           532       2024      4   SWE  Sweden                1.0
           533       2024      5   SWE  Sweden                1.0
           534       2024      6   SWE  Sweden                1.0
           535       2024      7   SWE  Sweden                1.0
           536       2024      8   SWE  Sweden                1.0
           537       2024      9   SWE  Sweden                1.0
           538       2024     10   SWE  Sweden                1.0
           539       2024     11   SWE  Sweden                1.0
           540       2024     12   SWE  Sweden                1.0
           541       2025      1   SWE  Sweden                1.5
           542       2025      2   SWE  Sweden                1.5
           543       2025      3   SWE  Sweden                1.5
           544       2025      4   SWE  Sweden                1.5
           545       2025      5   SWE  Sweden                1.5
           546       2025      6   SWE  Sweden                1.5
           547       2025      7   SWE  Sweden                1.5
           548       2025      8   SWE  Sweden                1.5
           549       2025      9   SWE  Sweden                1.5
           550       2025     10   SWE  Sweden                1.5
           551       2025     11   SWE  Sweden                1.5
           552       2025     12   SWE  Sweden                1.5
           553       2026      1   SWE  Sweden                2.0
           554       2026      2   SWE  Sweden                2.0
           555       2026      3   SWE  Sweden                2.0
           556       2026      4   SWE  Sweden                2.0
           557       2026      5   SWE  Sweden                2.0
           558       2026      6   SWE  Sweden                2.0
           559       2026      7   SWE  Sweden                2.0
           560       2026      8   SWE  Sweden                2.0
           561       2026      9   SWE  Sweden                2.0

                     imf_weo_ngdpd
country_id month_id
66         520             578.991
           521             578.991
           522             578.991
           523             578.991
           524             578.991
           525             578.991
           526             578.991
           527             578.991
           528             578.991
           529             604.827
           530             604.827
           531             604.827
           532             604.827
           533             604.827
           534             604.827
           535             604.827
           536             604.827
           537             604.827
           538             604.827
           539             604.827
           540             604.827
           541             668.999
           542             668.999
           543             668.999
           544             668.999
           545             668.999
           546             668.999
           547             668.999
           548             668.999
           549             668.999
           550             668.999
           551             668.999
           552             668.999
           553             760.481
           554             760.481
           555             760.481
           556             760.481
           557             760.481
           558             760.481
           559             760.481
           560             760.481
           561             760.481

In [80]:
print("All done!")

All done!